# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/subscription/cu_tracker.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/subscription/cu_tracker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*lavanet/lava/subscription/cu_tracker.proto\x12\x19lavanet.lava.subscription\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a\x14gogoproto/gogo.proto\"\x17\n\tTrackedCu\x12\n\n\x02\x63u\x18\x01 \x01(\x04\"T\n\x12\x43uTrackerTimerData\x12\r\n\x05\x62lock\x18\x01 \x01(\x04\x12/\n\x06\x63redit\x18\x02 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00\"T\n\rTrackedCuInfo\x12\x10\n\x08provider\x18\x01 \x01(\t\x12\x0f\n\x07\x63hainID\x18\x02 \x01(\t\x12\x11\n\ttrackedCu\x18\x03 \x01(\x04\x12\r\n\x05\x62lock\x18\x04 \x01(\x04\x42\x31Z/github.com/lavanet/lava/v2/x/subscription/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.subscription.cu_tracker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/lavanet/lava/v2/x/subscription/types'
  _globals['_CUTRACKERTIMERDATA'].fields_by_name['credit']._loaded_options = None
  _globals['_CUTRACKERTIMERDATA'].fields_by_name['credit']._serialized_options = b'\310\336\037\000'
  _globals['_TRACKEDCU']._serialized_start=127
  _globals['_TRACKEDCU']._serialized_end=150
  _globals['_CUTRACKERTIMERDATA']._serialized_start=152
  _globals['_CUTRACKERTIMERDATA']._serialized_end=236
  _globals['_TRACKEDCUINFO']._serialized_start=238
  _globals['_TRACKEDCUINFO']._serialized_end=322
# @@protoc_insertion_point(module_scope)
