# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/subscription/genesis.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/subscription/genesis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from lavanet.lava.subscription import params_pb2 as lavanet_dot_lava_dot_subscription_dot_params__pb2
from lavanet.lava.subscription import adjustment_pb2 as lavanet_dot_lava_dot_subscription_dot_adjustment__pb2
from lavanet.lava.fixationstore import fixation_pb2 as lavanet_dot_lava_dot_fixationstore_dot_fixation__pb2
from lavanet.lava.timerstore import timer_pb2 as lavanet_dot_lava_dot_timerstore_dot_timer__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'lavanet/lava/subscription/genesis.proto\x12\x19lavanet.lava.subscription\x1a\x14gogoproto/gogo.proto\x1a&lavanet/lava/subscription/params.proto\x1a*lavanet/lava/subscription/adjustment.proto\x1a)lavanet/lava/fixationstore/fixation.proto\x1a#lavanet/lava/timerstore/timer.proto\"\x8d\x03\n\x0cGenesisState\x12\x37\n\x06params\x18\x01 \x01(\x0b\x32!.lavanet.lava.subscription.ParamsB\x04\xc8\xde\x1f\x00\x12>\n\x06subsFS\x18\x02 \x01(\x0b\x32(.lavanet.lava.fixationstore.GenesisStateB\x04\xc8\xde\x1f\x00\x12;\n\x06subsTS\x18\x03 \x01(\x0b\x32%.lavanet.lava.timerstore.GenesisStateB\x04\xc8\xde\x1f\x00\x12\x43\n\x0b\x63uTrackerFS\x18\x04 \x01(\x0b\x32(.lavanet.lava.fixationstore.GenesisStateB\x04\xc8\xde\x1f\x00\x12@\n\x0b\x63uTrackerTS\x18\x05 \x01(\x0b\x32%.lavanet.lava.timerstore.GenesisStateB\x04\xc8\xde\x1f\x00\x12@\n\x0b\x61\x64justments\x18\x06 \x03(\x0b\x32%.lavanet.lava.subscription.AdjustmentB\x04\xc8\xde\x1f\x00\x42\x31Z/github.com/lavanet/lava/v2/x/subscription/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.subscription.genesis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/lavanet/lava/v2/x/subscription/types'
  _globals['_GENESISSTATE'].fields_by_name['params']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['params']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['subsFS']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['subsFS']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['subsTS']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['subsTS']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['cuTrackerFS']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['cuTrackerFS']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['cuTrackerTS']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['cuTrackerTS']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['adjustments']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['adjustments']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE']._serialized_start=257
  _globals['_GENESISSTATE']._serialized_end=654
# @@protoc_insertion_point(module_scope)
