# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/subscription/subscription.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/subscription/subscription.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,lavanet/lava/subscription/subscription.proto\x12\x19lavanet.lava.subscription\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a\x14gogoproto/gogo.proto\"\xba\x03\n\x0cSubscription\x12\x0f\n\x07\x63reator\x18\x01 \x01(\t\x12\x10\n\x08\x63onsumer\x18\x02 \x01(\t\x12\r\n\x05\x62lock\x18\x03 \x01(\x04\x12\x12\n\nplan_index\x18\x04 \x01(\t\x12\x12\n\nplan_block\x18\x05 \x01(\x04\x12\x17\n\x0f\x64uration_bought\x18\x06 \x01(\x04\x12\x15\n\rduration_left\x18\x07 \x01(\x04\x12\x19\n\x11month_expiry_time\x18\x08 \x01(\x04\x12\x16\n\x0emonth_cu_total\x18\n \x01(\x04\x12\x15\n\rmonth_cu_left\x18\x0b \x01(\x04\x12\x0f\n\x07\x63luster\x18\r \x01(\t\x12\x16\n\x0e\x64uration_total\x18\x0e \x01(\x04\x12J\n\x13\x66uture_subscription\x18\x10 \x01(\x0b\x32-.lavanet.lava.subscription.FutureSubscription\x12\x1e\n\x16\x61uto_renewal_next_plan\x18\x11 \x01(\t\x12/\n\x06\x63redit\x18\x12 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00J\x04\x08\t\x10\nJ\x04\x08\x0c\x10\rJ\x04\x08\x0f\x10\x10\"\x97\x01\n\x12\x46utureSubscription\x12\x0f\n\x07\x63reator\x18\x01 \x01(\t\x12\x12\n\nplan_index\x18\x02 \x01(\t\x12\x12\n\nplan_block\x18\x03 \x01(\x04\x12\x17\n\x0f\x64uration_bought\x18\x04 \x01(\x04\x12/\n\x06\x63redit\x18\x05 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00\x42\x31Z/github.com/lavanet/lava/v2/x/subscription/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.subscription.subscription_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/lavanet/lava/v2/x/subscription/types'
  _globals['_SUBSCRIPTION'].fields_by_name['credit']._loaded_options = None
  _globals['_SUBSCRIPTION'].fields_by_name['credit']._serialized_options = b'\310\336\037\000'
  _globals['_FUTURESUBSCRIPTION'].fields_by_name['credit']._loaded_options = None
  _globals['_FUTURESUBSCRIPTION'].fields_by_name['credit']._serialized_options = b'\310\336\037\000'
  _globals['_SUBSCRIPTION']._serialized_start=130
  _globals['_SUBSCRIPTION']._serialized_end=572
  _globals['_FUTURESUBSCRIPTION']._serialized_start=575
  _globals['_FUTURESUBSCRIPTION']._serialized_end=726
# @@protoc_insertion_point(module_scope)
