# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/subscription/tx.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/subscription/tx.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from lavanet.lava.projects import project_pb2 as lavanet_dot_lava_dot_projects_dot_project__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"lavanet/lava/subscription/tx.proto\x12\x19lavanet.lava.subscription\x1a\x11\x61mino/amino.proto\x1a#lavanet/lava/projects/project.proto\x1a\x14gogoproto/gogo.proto\"\x99\x01\n\x06MsgBuy\x12\x0f\n\x07\x63reator\x18\x01 \x01(\t\x12\x10\n\x08\x63onsumer\x18\x02 \x01(\t\x12\r\n\x05index\x18\x03 \x01(\t\x12\x10\n\x08\x64uration\x18\x04 \x01(\x04\x12\x14\n\x0c\x61uto_renewal\x18\x06 \x01(\x08\x12\x18\n\x10\x61\x64vance_purchase\x18\x07 \x01(\x08:\x15\x8a\xe7\xb0*\x10subscription/BuyJ\x04\x08\x05\x10\x06\"\x10\n\x0eMsgBuyResponse\"~\n\rMsgAddProject\x12\x0f\n\x07\x63reator\x18\x01 \x01(\t\x12>\n\x0cproject_data\x18\x02 \x01(\x0b\x32\".lavanet.lava.projects.ProjectDataB\x04\xc8\xde\x1f\x00:\x1c\x8a\xe7\xb0*\x17subscription/AddProject\"\x17\n\x15MsgAddProjectResponse\"L\n\rMsgDelProject\x12\x0f\n\x07\x63reator\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t:\x1c\x8a\xe7\xb0*\x17subscription/DelProject\"\x17\n\x15MsgDelProjectResponse\"q\n\x0eMsgAutoRenewal\x12\x0f\n\x07\x63reator\x18\x01 \x01(\t\x12\x0e\n\x06\x65nable\x18\x02 \x01(\x08\x12\x10\n\x08\x63onsumer\x18\x03 \x01(\t\x12\r\n\x05index\x18\x04 \x01(\t:\x1d\x8a\xe7\xb0*\x18subscription/AutoRenewal\"\x18\n\x16MsgAutoRenewalResponse2\x9b\x03\n\x03Msg\x12S\n\x03\x42uy\x12!.lavanet.lava.subscription.MsgBuy\x1a).lavanet.lava.subscription.MsgBuyResponse\x12h\n\nAddProject\x12(.lavanet.lava.subscription.MsgAddProject\x1a\x30.lavanet.lava.subscription.MsgAddProjectResponse\x12h\n\nDelProject\x12(.lavanet.lava.subscription.MsgDelProject\x1a\x30.lavanet.lava.subscription.MsgDelProjectResponse\x12k\n\x0b\x41utoRenewal\x12).lavanet.lava.subscription.MsgAutoRenewal\x1a\x31.lavanet.lava.subscription.MsgAutoRenewalResponseB1Z/github.com/lavanet/lava/v2/x/subscription/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.subscription.tx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/lavanet/lava/v2/x/subscription/types'
  _globals['_MSGBUY']._loaded_options = None
  _globals['_MSGBUY']._serialized_options = b'\212\347\260*\020subscription/Buy'
  _globals['_MSGADDPROJECT'].fields_by_name['project_data']._loaded_options = None
  _globals['_MSGADDPROJECT'].fields_by_name['project_data']._serialized_options = b'\310\336\037\000'
  _globals['_MSGADDPROJECT']._loaded_options = None
  _globals['_MSGADDPROJECT']._serialized_options = b'\212\347\260*\027subscription/AddProject'
  _globals['_MSGDELPROJECT']._loaded_options = None
  _globals['_MSGDELPROJECT']._serialized_options = b'\212\347\260*\027subscription/DelProject'
  _globals['_MSGAUTORENEWAL']._loaded_options = None
  _globals['_MSGAUTORENEWAL']._serialized_options = b'\212\347\260*\030subscription/AutoRenewal'
  _globals['_MSGBUY']._serialized_start=144
  _globals['_MSGBUY']._serialized_end=297
  _globals['_MSGBUYRESPONSE']._serialized_start=299
  _globals['_MSGBUYRESPONSE']._serialized_end=315
  _globals['_MSGADDPROJECT']._serialized_start=317
  _globals['_MSGADDPROJECT']._serialized_end=443
  _globals['_MSGADDPROJECTRESPONSE']._serialized_start=445
  _globals['_MSGADDPROJECTRESPONSE']._serialized_end=468
  _globals['_MSGDELPROJECT']._serialized_start=470
  _globals['_MSGDELPROJECT']._serialized_end=546
  _globals['_MSGDELPROJECTRESPONSE']._serialized_start=548
  _globals['_MSGDELPROJECTRESPONSE']._serialized_end=571
  _globals['_MSGAUTORENEWAL']._serialized_start=573
  _globals['_MSGAUTORENEWAL']._serialized_end=686
  _globals['_MSGAUTORENEWALRESPONSE']._serialized_start=688
  _globals['_MSGAUTORENEWALRESPONSE']._serialized_end=712
  _globals['_MSG']._serialized_start=715
  _globals['_MSG']._serialized_end=1126
# @@protoc_insertion_point(module_scope)
