# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/rewards/base_pay.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/rewards/base_pay.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#lavanet/lava/rewards/base_pay.proto\x12\x14lavanet.lava.rewards\x1a\x11\x61mino/amino.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\"\xaf\x01\n\x07\x42\x61sePay\x12K\n\x05total\x18\x01 \x01(\tB<\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Int\xd2\xb4-\ncosmos.Int\x12\x45\n\rtotalAdjusted\x18\x02 \x01(\tB.\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\x12\x10\n\x08iprpc_cu\x18\x03 \x01(\x04\"m\n\x10\x42\x61sePayWithIndex\x12\x10\n\x08provider\x18\x01 \x01(\t\x12\x10\n\x08\x63hain_id\x18\x02 \x01(\t\x12\x35\n\x08\x62\x61se_pay\x18\x03 \x01(\x0b\x32\x1d.lavanet.lava.rewards.BasePayB\x04\xc8\xde\x1f\x00\x42,Z*github.com/lavanet/lava/v2/x/rewards/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.rewards.base_pay_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/lavanet/lava/v2/x/rewards/types'
  _globals['_BASEPAY'].fields_by_name['total']._loaded_options = None
  _globals['_BASEPAY'].fields_by_name['total']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Int\322\264-\ncosmos.Int'
  _globals['_BASEPAY'].fields_by_name['totalAdjusted']._loaded_options = None
  _globals['_BASEPAY'].fields_by_name['totalAdjusted']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec'
  _globals['_BASEPAYWITHINDEX'].fields_by_name['base_pay']._loaded_options = None
  _globals['_BASEPAYWITHINDEX'].fields_by_name['base_pay']._serialized_options = b'\310\336\037\000'
  _globals['_BASEPAY']._serialized_start=162
  _globals['_BASEPAY']._serialized_end=337
  _globals['_BASEPAYWITHINDEX']._serialized_start=339
  _globals['_BASEPAYWITHINDEX']._serialized_end=448
# @@protoc_insertion_point(module_scope)
