# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/rewards/params.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/rewards/params.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!lavanet/lava/rewards/params.proto\x12\x14lavanet.lava.rewards\x1a\x14gogoproto/gogo.proto\"\xc8\x04\n\x06Params\x12\x65\n\x11min_bonded_target\x18\x01 \x01(\tBJ\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xf2\xde\x1f\x18yaml:\"min_bonded_target\"\x12\x65\n\x11max_bonded_target\x18\x02 \x01(\tBJ\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xf2\xde\x1f\x18yaml:\"max_bonded_target\"\x12W\n\nlow_factor\x18\x03 \x01(\tBC\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xf2\xde\x1f\x11yaml:\"low_factor\"\x12g\n\x12leftover_burn_rate\x18\x04 \x01(\tBK\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xf2\xde\x1f\x19yaml:\"leftover_burn_rate\"\x12\x18\n\x10max_reward_boost\x18\x05 \x01(\x04\x12\x8d\x01\n%validators_subscription_participation\x18\x06 \x01(\tB^\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xf2\xde\x1f,yaml:\"validators_subscription_participation\":\x04\x98\xa0\x1f\x00\x42,Z*github.com/lavanet/lava/v2/x/rewards/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.rewards.params_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/lavanet/lava/v2/x/rewards/types'
  _globals['_PARAMS'].fields_by_name['min_bonded_target']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['min_bonded_target']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\362\336\037\030yaml:\"min_bonded_target\"'
  _globals['_PARAMS'].fields_by_name['max_bonded_target']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['max_bonded_target']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\362\336\037\030yaml:\"max_bonded_target\"'
  _globals['_PARAMS'].fields_by_name['low_factor']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['low_factor']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\362\336\037\021yaml:\"low_factor\"'
  _globals['_PARAMS'].fields_by_name['leftover_burn_rate']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['leftover_burn_rate']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\362\336\037\031yaml:\"leftover_burn_rate\"'
  _globals['_PARAMS'].fields_by_name['validators_subscription_participation']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['validators_subscription_participation']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\362\336\037,yaml:\"validators_subscription_participation\"'
  _globals['_PARAMS']._loaded_options = None
  _globals['_PARAMS']._serialized_options = b'\230\240\037\000'
  _globals['_PARAMS']._serialized_start=82
  _globals['_PARAMS']._serialized_end=666
# @@protoc_insertion_point(module_scope)
