# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/rewards/tx.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/rewards/tx.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dlavanet/lava/rewards/tx.proto\x12\x14lavanet.lava.rewards\x1a\x11\x61mino/amino.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a\x14gogoproto/gogo.proto\"\x98\x01\n\x0fMsgSetIprpcData\x12\x11\n\tauthority\x18\x01 \x01(\t\x12\x37\n\x0emin_iprpc_cost\x18\x02 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00\x12\x1b\n\x13iprpc_subscriptions\x18\x03 \x03(\t:\x1c\x8a\xe7\xb0*\x17rewards/MsgSetIprpcData\"\x19\n\x17MsgSetIprpcDataResponse\"\xb8\x01\n\x0cMsgFundIprpc\x12\x0f\n\x07\x63reator\x18\x01 \x01(\t\x12\x10\n\x08\x64uration\x18\x02 \x01(\x04\x12\\\n\x07\x61mounts\x18\x03 \x03(\x0b\x32\x19.cosmos.base.v1beta1.CoinB0\xc8\xde\x1f\x00\xaa\xdf\x1f(github.com/cosmos/cosmos-sdk/types.Coins\x12\x0c\n\x04spec\x18\x04 \x01(\t:\x19\x8a\xe7\xb0*\x14rewards/MsgFundIprpc\"\x16\n\x14MsgFundIprpcResponse2\xc8\x01\n\x03Msg\x12\x64\n\x0cSetIprpcData\x12%.lavanet.lava.rewards.MsgSetIprpcData\x1a-.lavanet.lava.rewards.MsgSetIprpcDataResponse\x12[\n\tFundIprpc\x12\".lavanet.lava.rewards.MsgFundIprpc\x1a*.lavanet.lava.rewards.MsgFundIprpcResponseB,Z*github.com/lavanet/lava/v2/x/rewards/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.rewards.tx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/lavanet/lava/v2/x/rewards/types'
  _globals['_MSGSETIPRPCDATA'].fields_by_name['min_iprpc_cost']._loaded_options = None
  _globals['_MSGSETIPRPCDATA'].fields_by_name['min_iprpc_cost']._serialized_options = b'\310\336\037\000'
  _globals['_MSGSETIPRPCDATA']._loaded_options = None
  _globals['_MSGSETIPRPCDATA']._serialized_options = b'\212\347\260*\027rewards/MsgSetIprpcData'
  _globals['_MSGFUNDIPRPC'].fields_by_name['amounts']._loaded_options = None
  _globals['_MSGFUNDIPRPC'].fields_by_name['amounts']._serialized_options = b'\310\336\037\000\252\337\037(github.com/cosmos/cosmos-sdk/types.Coins'
  _globals['_MSGFUNDIPRPC']._loaded_options = None
  _globals['_MSGFUNDIPRPC']._serialized_options = b'\212\347\260*\024rewards/MsgFundIprpc'
  _globals['_MSGSETIPRPCDATA']._serialized_start=129
  _globals['_MSGSETIPRPCDATA']._serialized_end=281
  _globals['_MSGSETIPRPCDATARESPONSE']._serialized_start=283
  _globals['_MSGSETIPRPCDATARESPONSE']._serialized_end=308
  _globals['_MSGFUNDIPRPC']._serialized_start=311
  _globals['_MSGFUNDIPRPC']._serialized_end=495
  _globals['_MSGFUNDIPRPCRESPONSE']._serialized_start=497
  _globals['_MSGFUNDIPRPCRESPONSE']._serialized_end=519
  _globals['_MSG']._serialized_start=522
  _globals['_MSG']._serialized_end=722
# @@protoc_insertion_point(module_scope)
