# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/timerstore/query.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/timerstore/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from lavanet.lava.timerstore import timer_pb2 as lavanet_dot_lava_dot_timerstore_dot_timer__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#lavanet/lava/timerstore/query.proto\x12\x17lavanet.lava.timerstore\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\x1a#lavanet/lava/timerstore/timer.proto\":\n\x15QueryAllTimersRequest\x12\x11\n\tstore_key\x18\x01 \x01(\t\x12\x0e\n\x06prefix\x18\x02 \x01(\t\"[\n\tTimerInfo\x12\x13\n\tblockTime\x18\x01 \x01(\tH\x00\x12\x15\n\x0b\x62lockHeight\x18\x02 \x01(\x04H\x00\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x42\x07\n\x05\x62lock\"\xa2\x01\n\x16QueryAllTimersResponse\x12;\n\x0f\x62lockTimeTimers\x18\x01 \x03(\x0b\x32\".lavanet.lava.timerstore.TimerInfo\x12=\n\x11\x62lockHeightTimers\x18\x02 \x03(\x0b\x32\".lavanet.lava.timerstore.TimerInfo\x12\x0c\n\x04tick\x18\x03 \x01(\t\"\x17\n\x15QueryStoreKeysRequest\"6\n\x11StoreKeyAndPrefix\x12\x11\n\tstore_key\x18\x01 \x01(\t\x12\x0e\n\x06prefix\x18\x02 \x01(\t\"X\n\x16QueryStoreKeysResponse\x12>\n\x04keys\x18\x01 \x03(\x0b\x32*.lavanet.lava.timerstore.StoreKeyAndPrefixB\x04\xc8\xde\x1f\x00\"5\n\x10QueryNextRequest\x12\x11\n\tstore_key\x18\x01 \x01(\t\x12\x0e\n\x06prefix\x18\x02 \x01(\t\"Q\n\x11QueryNextResponse\x12\x17\n\x0fnextBlockHeight\x18\x01 \x01(\x04\x12\x15\n\rnextBlockTime\x18\x02 \x01(\t\x12\x0c\n\x04tick\x18\x03 \x01(\t2\xf0\x03\n\x05Query\x12\xae\x01\n\tAllTimers\x12..lavanet.lava.timerstore.QueryAllTimersRequest\x1a/.lavanet.lava.timerstore.QueryAllTimersResponse\"@\x82\xd3\xe4\x93\x02:\x12\x38/lavanet/lava/timerstore/all_timers/{store_key}/{prefix}\x12\x99\x01\n\tStoreKeys\x12..lavanet.lava.timerstore.QueryStoreKeysRequest\x1a/.lavanet.lava.timerstore.QueryStoreKeysResponse\"+\x82\xd3\xe4\x93\x02%\x12#/lavanet/lava/timerstore/store_keys\x12\x99\x01\n\x04Next\x12).lavanet.lava.timerstore.QueryNextRequest\x1a*.lavanet.lava.timerstore.QueryNextResponse\":\x82\xd3\xe4\x93\x02\x34\x12\x32/lavanet/lava/timerstore/next/{store_key}/{prefix}B/Z-github.com/lavanet/lava/v2/x/timerstore/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.timerstore.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-github.com/lavanet/lava/v2/x/timerstore/types'
  _globals['_QUERYSTOREKEYSRESPONSE'].fields_by_name['keys']._loaded_options = None
  _globals['_QUERYSTOREKEYSRESPONSE'].fields_by_name['keys']._serialized_options = b'\310\336\037\000'
  _globals['_QUERY'].methods_by_name['AllTimers']._loaded_options = None
  _globals['_QUERY'].methods_by_name['AllTimers']._serialized_options = b'\202\323\344\223\002:\0228/lavanet/lava/timerstore/all_timers/{store_key}/{prefix}'
  _globals['_QUERY'].methods_by_name['StoreKeys']._loaded_options = None
  _globals['_QUERY'].methods_by_name['StoreKeys']._serialized_options = b'\202\323\344\223\002%\022#/lavanet/lava/timerstore/store_keys'
  _globals['_QUERY'].methods_by_name['Next']._loaded_options = None
  _globals['_QUERY'].methods_by_name['Next']._serialized_options = b'\202\323\344\223\0024\0222/lavanet/lava/timerstore/next/{store_key}/{prefix}'
  _globals['_QUERYALLTIMERSREQUEST']._serialized_start=153
  _globals['_QUERYALLTIMERSREQUEST']._serialized_end=211
  _globals['_TIMERINFO']._serialized_start=213
  _globals['_TIMERINFO']._serialized_end=304
  _globals['_QUERYALLTIMERSRESPONSE']._serialized_start=307
  _globals['_QUERYALLTIMERSRESPONSE']._serialized_end=469
  _globals['_QUERYSTOREKEYSREQUEST']._serialized_start=471
  _globals['_QUERYSTOREKEYSREQUEST']._serialized_end=494
  _globals['_STOREKEYANDPREFIX']._serialized_start=496
  _globals['_STOREKEYANDPREFIX']._serialized_end=550
  _globals['_QUERYSTOREKEYSRESPONSE']._serialized_start=552
  _globals['_QUERYSTOREKEYSRESPONSE']._serialized_end=640
  _globals['_QUERYNEXTREQUEST']._serialized_start=642
  _globals['_QUERYNEXTREQUEST']._serialized_end=695
  _globals['_QUERYNEXTRESPONSE']._serialized_start=697
  _globals['_QUERYNEXTRESPONSE']._serialized_end=778
  _globals['_QUERY']._serialized_start=781
  _globals['_QUERY']._serialized_end=1277
# @@protoc_insertion_point(module_scope)
