image: nikolaik/python-nodejs:python3.12-nodejs20

pipelines:
  branches:
    main:
      - step:
          caches:
            - pip
          script:
            - apt-get update
            - apt-get install poppler-utils -y
            - export POSTGRES_USER=hello_django
            - export POSTGRES_DB=hello_django_dev
            - export POSTGRES_PASSWORD=hello_django
            - pip install -r requirements.txt
            - python manage.py test
          services:
            - postgres
      - step:
          deployment: Production
          script:
            - git checkout -b prod-pipeline
            - git config user.email autocommit@webisoft.com
            - git config user.name Pipeline
            - git commit --allow-empty -m "Build"
            - git push --force
    stage:
      - step:
          caches:
            - pip
          script:
            - apt-get update
            - apt-get install poppler-utils -y
            - export POSTGRES_USER=hello_django
            - export POSTGRES_DB=hello_django_dev
            - export POSTGRES_PASSWORD=hello_django
            - pip install -r requirements.txt
            - python manage.py test
          services:
            - postgres
      - step:
          deployment: Staging
          script:
            - git checkout -b stage-pipeline
            - git config user.email autocommit@webisoft.com
            - git config user.name Pipeline
            - git commit --allow-empty -m "Build"
            - git push --force

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: "hello_django_dev"
        POSTGRES_USER: "hello_django"
        POSTGRES_PASSWORD: "hello_django"