# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tendermint/services/block/v1/block_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'tendermint/services/block/v1/block_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tendermint.services.block.v1 import block_pb2 as tendermint_dot_services_dot_block_dot_v1_dot_block__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0tendermint/services/block/v1/block_service.proto\x12\x1ctendermint.services.block.v1\x1a(tendermint/services/block/v1/block.proto2\x85\x02\n\x0c\x42lockService\x12r\n\x0bGetByHeight\x12\x30.tendermint.services.block.v1.GetByHeightRequest\x1a\x31.tendermint.services.block.v1.GetByHeightResponse\x12\x80\x01\n\x0fGetLatestHeight\x12\x34.tendermint.services.block.v1.GetLatestHeightRequest\x1a\x35.tendermint.services.block.v1.GetLatestHeightResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tendermint.services.block.v1.block_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLOCKSERVICE']._serialized_start=125
  _globals['_BLOCKSERVICE']._serialized_end=386
# @@protoc_insertion_point(module_scope)
