# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/projects/genesis.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/projects/genesis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from lavanet.lava.projects import params_pb2 as lavanet_dot_lava_dot_projects_dot_params__pb2
from lavanet.lava.fixationstore import fixation_pb2 as lavanet_dot_lava_dot_fixationstore_dot_fixation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#lavanet/lava/projects/genesis.proto\x12\x15lavanet.lava.projects\x1a\x14gogoproto/gogo.proto\x1a\"lavanet/lava/projects/params.proto\x1a)lavanet/lava/fixationstore/fixation.proto\"\xcc\x01\n\x0cGenesisState\x12\x33\n\x06params\x18\x01 \x01(\x0b\x32\x1d.lavanet.lava.projects.ParamsB\x04\xc8\xde\x1f\x00\x12\x42\n\nprojectsFS\x18\x02 \x01(\x0b\x32(.lavanet.lava.fixationstore.GenesisStateB\x04\xc8\xde\x1f\x00\x12\x43\n\x0b\x64\x65veloperFS\x18\x03 \x01(\x0b\x32(.lavanet.lava.fixationstore.GenesisStateB\x04\xc8\xde\x1f\x00\x42-Z+github.com/lavanet/lava/v2/x/projects/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.projects.genesis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/lavanet/lava/v2/x/projects/types'
  _globals['_GENESISSTATE'].fields_by_name['params']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['params']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['projectsFS']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['projectsFS']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['developerFS']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['developerFS']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE']._serialized_start=164
  _globals['_GENESISSTATE']._serialized_end=368
# @@protoc_insertion_point(module_scope)
