# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/epochstorage/endpoint.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/epochstorage/endpoint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(lavanet/lava/epochstorage/endpoint.proto\x12\x19lavanet.lava.epochstorage\"q\n\x08\x45ndpoint\x12\x0e\n\x06iPPORT\x18\x01 \x01(\t\x12\x13\n\x0bgeolocation\x18\x03 \x01(\x05\x12\x0e\n\x06\x61\x64\x64ons\x18\x04 \x03(\t\x12\x16\n\x0e\x61pi_interfaces\x18\x05 \x03(\t\x12\x12\n\nextensions\x18\x06 \x03(\tJ\x04\x08\x02\x10\x03\x42\x31Z/github.com/lavanet/lava/v2/x/epochstorage/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.epochstorage.endpoint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/lavanet/lava/v2/x/epochstorage/types'
  _globals['_ENDPOINT']._serialized_start=71
  _globals['_ENDPOINT']._serialized_end=184
# @@protoc_insertion_point(module_scope)
