# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/epochstorage/params.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/epochstorage/params.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&lavanet/lava/epochstorage/params.proto\x12\x19lavanet.lava.epochstorage\x1a\x14gogoproto/gogo.proto\"\xb4\x01\n\x06Params\x12,\n\x0b\x65pochBlocks\x18\x02 \x01(\x04\x42\x17\xf2\xde\x1f\x13yaml:\"epoch_blocks\"\x12/\n\x0c\x65pochsToSave\x18\x03 \x01(\x04\x42\x19\xf2\xde\x1f\x15yaml:\"epochs_to_save\"\x12\x39\n\x11latestParamChange\x18\x04 \x01(\x04\x42\x1e\xf2\xde\x1f\x1ayaml:\"latest_param_change\":\x04\x98\xa0\x1f\x00J\x04\x08\x01\x10\x02J\x04\x08\x05\x10\x06\x42\x31Z/github.com/lavanet/lava/v2/x/epochstorage/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.epochstorage.params_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/lavanet/lava/v2/x/epochstorage/types'
  _globals['_PARAMS'].fields_by_name['epochBlocks']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['epochBlocks']._serialized_options = b'\362\336\037\023yaml:\"epoch_blocks\"'
  _globals['_PARAMS'].fields_by_name['epochsToSave']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['epochsToSave']._serialized_options = b'\362\336\037\025yaml:\"epochs_to_save\"'
  _globals['_PARAMS'].fields_by_name['latestParamChange']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['latestParamChange']._serialized_options = b'\362\336\037\032yaml:\"latest_param_change\"'
  _globals['_PARAMS']._loaded_options = None
  _globals['_PARAMS']._serialized_options = b'\230\240\037\000'
  _globals['_PARAMS']._serialized_start=92
  _globals['_PARAMS']._serialized_end=272
# @@protoc_insertion_point(module_scope)
