# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/downtime/v1/genesis.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/downtime/v1/genesis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lavanet.lava.downtime.v1 import downtime_pb2 as lavanet_dot_lava_dot_downtime_dot_v1_dot_downtime__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&lavanet/lava/downtime/v1/genesis.proto\x12\x18lavanet.lava.downtime.v1\x1a\'lavanet/lava/downtime/v1/downtime.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14gogoproto/gogo.proto\"\xbc\x01\n\x0cGenesisState\x12\x36\n\x06params\x18\x01 \x01(\x0b\x32 .lavanet.lava.downtime.v1.ParamsB\x04\xc8\xde\x1f\x00\x12\x35\n\tdowntimes\x18\x02 \x03(\x0b\x32\".lavanet.lava.downtime.v1.Downtime\x12=\n\x0flast_block_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x08\xc8\xde\x1f\x01\x90\xdf\x1f\x01\x42*Z(github.com/lavanet/lava/v2/x/downtime/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.downtime.v1.genesis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/lavanet/lava/v2/x/downtime/v1'
  _globals['_GENESISSTATE'].fields_by_name['params']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['params']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['last_block_time']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['last_block_time']._serialized_options = b'\310\336\037\001\220\337\037\001'
  _globals['_GENESISSTATE']._serialized_start=165
  _globals['_GENESISSTATE']._serialized_end=353
# @@protoc_insertion_point(module_scope)
