# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/rewards/genesis.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/rewards/genesis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from lavanet.lava.rewards import base_pay_pb2 as lavanet_dot_lava_dot_rewards_dot_base__pay__pb2
from lavanet.lava.rewards import iprpc_pb2 as lavanet_dot_lava_dot_rewards_dot_iprpc__pb2
from lavanet.lava.rewards import params_pb2 as lavanet_dot_lava_dot_rewards_dot_params__pb2
from lavanet.lava.timerstore import timer_pb2 as lavanet_dot_lava_dot_timerstore_dot_timer__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"lavanet/lava/rewards/genesis.proto\x12\x14lavanet.lava.rewards\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a\x14gogoproto/gogo.proto\x1a#lavanet/lava/rewards/base_pay.proto\x1a lavanet/lava/rewards/iprpc.proto\x1a!lavanet/lava/rewards/params.proto\x1a#lavanet/lava/timerstore/timer.proto\"\xfe\x02\n\x0cGenesisState\x12\x32\n\x06params\x18\x01 \x01(\x0b\x32\x1c.lavanet.lava.rewards.ParamsB\x04\xc8\xde\x1f\x00\x12\x44\n\x0frefillRewardsTS\x18\x02 \x01(\x0b\x32%.lavanet.lava.timerstore.GenesisStateB\x04\xc8\xde\x1f\x00\x12?\n\tbase_pays\x18\x03 \x03(\x0b\x32&.lavanet.lava.rewards.BasePayWithIndexB\x04\xc8\xde\x1f\x00\x12\x1b\n\x13iprpc_subscriptions\x18\x04 \x03(\t\x12\x37\n\x0emin_iprpc_cost\x18\x05 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00\x12>\n\riprpc_rewards\x18\x06 \x03(\x0b\x32!.lavanet.lava.rewards.IprpcRewardB\x04\xc8\xde\x1f\x00\x12\x1d\n\x15iprpc_rewards_current\x18\x07 \x01(\x04\x42,Z*github.com/lavanet/lava/v2/x/rewards/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.rewards.genesis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/lavanet/lava/v2/x/rewards/types'
  _globals['_GENESISSTATE'].fields_by_name['params']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['params']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['refillRewardsTS']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['refillRewardsTS']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['base_pays']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['base_pays']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['min_iprpc_cost']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['min_iprpc_cost']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['iprpc_rewards']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['iprpc_rewards']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE']._serialized_start=258
  _globals['_GENESISSTATE']._serialized_end=640
# @@protoc_insertion_point(module_scope)
