# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/rewards/iprpc.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/rewards/iprpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n lavanet/lava/rewards/iprpc.proto\x12\x14lavanet.lava.rewards\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\"S\n\x0bIprpcReward\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x38\n\nspec_funds\x18\x02 \x03(\x0b\x32\x1e.lavanet.lava.rewards.SpecfundB\x04\xc8\xde\x1f\x00\"s\n\x08Specfund\x12\x0c\n\x04spec\x18\x01 \x01(\t\x12Y\n\x04\x66und\x18\x02 \x03(\x0b\x32\x19.cosmos.base.v1beta1.CoinB0\xc8\xde\x1f\x00\xaa\xdf\x1f(github.com/cosmos/cosmos-sdk/types.CoinsB,Z*github.com/lavanet/lava/v2/x/rewards/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.rewards.iprpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/lavanet/lava/v2/x/rewards/types'
  _globals['_IPRPCREWARD'].fields_by_name['spec_funds']._loaded_options = None
  _globals['_IPRPCREWARD'].fields_by_name['spec_funds']._serialized_options = b'\310\336\037\000'
  _globals['_SPECFUND'].fields_by_name['fund']._loaded_options = None
  _globals['_SPECFUND'].fields_by_name['fund']._serialized_options = b'\310\336\037\000\252\337\037(github.com/cosmos/cosmos-sdk/types.Coins'
  _globals['_IPRPCREWARD']._serialized_start=112
  _globals['_IPRPCREWARD']._serialized_end=195
  _globals['_SPECFUND']._serialized_start=197
  _globals['_SPECFUND']._serialized_end=312
# @@protoc_insertion_point(module_scope)
