# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/downtime/v1/downtime.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/downtime/v1/downtime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'lavanet/lava/downtime/v1/downtime.proto\x12\x18lavanet.lava.downtime.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14gogoproto/gogo.proto\"\x85\x01\n\x06Params\x12>\n\x11\x64owntime_duration\x18\x01 \x01(\x0b\x32\x19.google.protobuf.DurationB\x08\xc8\xde\x1f\x00\x98\xdf\x1f\x01\x12;\n\x0e\x65poch_duration\x18\x02 \x01(\x0b\x32\x19.google.protobuf.DurationB\x08\xc8\xde\x1f\x00\x98\xdf\x1f\x01\"P\n\x08\x44owntime\x12\r\n\x05\x62lock\x18\x01 \x01(\x04\x12\x35\n\x08\x64uration\x18\x02 \x01(\x0b\x32\x19.google.protobuf.DurationB\x08\xc8\xde\x1f\x00\x98\xdf\x1f\x01\x42*Z(github.com/lavanet/lava/v2/x/downtime/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.downtime.v1.downtime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/lavanet/lava/v2/x/downtime/v1'
  _globals['_PARAMS'].fields_by_name['downtime_duration']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['downtime_duration']._serialized_options = b'\310\336\037\000\230\337\037\001'
  _globals['_PARAMS'].fields_by_name['epoch_duration']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['epoch_duration']._serialized_options = b'\310\336\037\000\230\337\037\001'
  _globals['_DOWNTIME'].fields_by_name['duration']._loaded_options = None
  _globals['_DOWNTIME'].fields_by_name['duration']._serialized_options = b'\310\336\037\000\230\337\037\001'
  _globals['_PARAMS']._serialized_start=157
  _globals['_PARAMS']._serialized_end=290
  _globals['_DOWNTIME']._serialized_start=292
  _globals['_DOWNTIME']._serialized_end=372
# @@protoc_insertion_point(module_scope)
