# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/downtime/v1/query.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/downtime/v1/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from lavanet.lava.downtime.v1 import downtime_pb2 as lavanet_dot_lava_dot_downtime_dot_v1_dot_downtime__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$lavanet/lava/downtime/v1/query.proto\x12\x18lavanet.lava.downtime.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\'lavanet/lava/downtime/v1/downtime.proto\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\"1\n\x14QueryDowntimeRequest\x12\x19\n\x11\x65poch_start_block\x18\x01 \x01(\x04\"b\n\x15QueryDowntimeResponse\x12I\n\x1c\x63umulative_downtime_duration\x18\x02 \x01(\x0b\x32\x19.google.protobuf.DurationB\x08\xc8\xde\x1f\x00\x98\xdf\x1f\x01\"\x14\n\x12QueryParamsRequest\"G\n\x13QueryParamsResponse\x12\x30\n\x06params\x18\x01 \x01(\x0b\x32 .lavanet.lava.downtime.v1.Params2\xc3\x02\n\x05Query\x12\x94\x01\n\x0bQueryParams\x12,.lavanet.lava.downtime.v1.QueryParamsRequest\x1a-.lavanet.lava.downtime.v1.QueryParamsResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /lavanet/lava/downtime/v1/params\x12\xa2\x01\n\rQueryDowntime\x12..lavanet.lava.downtime.v1.QueryDowntimeRequest\x1a/.lavanet.lava.downtime.v1.QueryDowntimeResponse\"0\x82\xd3\xe4\x93\x02*\x12(/lavanet/lava/downtime/v1/query_downtimeB*Z(github.com/lavanet/lava/v2/x/downtime/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.downtime.v1.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/lavanet/lava/v2/x/downtime/v1'
  _globals['_QUERYDOWNTIMERESPONSE'].fields_by_name['cumulative_downtime_duration']._loaded_options = None
  _globals['_QUERYDOWNTIMERESPONSE'].fields_by_name['cumulative_downtime_duration']._serialized_options = b'\310\336\037\000\230\337\037\001'
  _globals['_QUERY'].methods_by_name['QueryParams']._loaded_options = None
  _globals['_QUERY'].methods_by_name['QueryParams']._serialized_options = b'\202\323\344\223\002\"\022 /lavanet/lava/downtime/v1/params'
  _globals['_QUERY'].methods_by_name['QueryDowntime']._loaded_options = None
  _globals['_QUERY'].methods_by_name['QueryDowntime']._serialized_options = b'\202\323\344\223\002*\022(/lavanet/lava/downtime/v1/query_downtime'
  _globals['_QUERYDOWNTIMEREQUEST']._serialized_start=191
  _globals['_QUERYDOWNTIMEREQUEST']._serialized_end=240
  _globals['_QUERYDOWNTIMERESPONSE']._serialized_start=242
  _globals['_QUERYDOWNTIMERESPONSE']._serialized_end=340
  _globals['_QUERYPARAMSREQUEST']._serialized_start=342
  _globals['_QUERYPARAMSREQUEST']._serialized_end=362
  _globals['_QUERYPARAMSRESPONSE']._serialized_start=364
  _globals['_QUERYPARAMSRESPONSE']._serialized_end=435
  _globals['_QUERY']._serialized_start=438
  _globals['_QUERY']._serialized_end=761
# @@protoc_insertion_point(module_scope)
