# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cosmos/streaming/v1/grpc.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'cosmos/streaming/v1/grpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63osmos/streaming/v1/grpc.proto\x12\x13\x63osmos.streaming.v1\"\xa1\x01\n\x19ListenDeliverBlockRequest\x12\x14\n\x0c\x62lock_height\x18\x01 \x01(\x03\x12\x0b\n\x03txs\x18\x02 \x03(\x0c\x12*\n\x06\x65vents\x18\x03 \x03(\x0b\x32\x1a.cosmos.streaming.v1.Event\x12\x35\n\ntx_results\x18\x04 \x03(\x0b\x32!.cosmos.streaming.v1.ExecTxResult\"\x1c\n\x1aListenDeliverBlockResponse\"y\n\x19ListenStateChangesRequest\x12\x14\n\x0c\x62lock_height\x18\x01 \x01(\x03\x12\x34\n\nchange_set\x18\x02 \x03(\x0b\x32 .cosmos.streaming.v1.StoreKVPair\x12\x10\n\x08\x61pp_hash\x18\x03 \x01(\x0c\"\x1c\n\x1aListenStateChangesResponse\"J\n\x0bStoreKVPair\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0c\x12\x0b\n\x03key\x18\x02 \x01(\x0c\x12\r\n\x05value\x18\x03 \x01(\x0c\x12\x0e\n\x06\x64\x65lete\x18\x04 \x01(\x08\"N\n\x05\x45vent\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x37\n\nattributes\x18\x02 \x03(\x0b\x32#.cosmos.streaming.v1.EventAttribute\",\n\x0e\x45ventAttribute\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\xaa\x01\n\x0c\x45xecTxResult\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0b\n\x03log\x18\x03 \x01(\t\x12\x0c\n\x04info\x18\x04 \x01(\t\x12\x12\n\ngas_wanted\x18\x05 \x01(\x03\x12\x10\n\x08gas_used\x18\x06 \x01(\x03\x12*\n\x06\x65vents\x18\x07 \x03(\x0b\x32\x1a.cosmos.streaming.v1.Event\x12\x11\n\tcodespace\x18\x08 \x01(\t2\xff\x01\n\x0fListenerService\x12u\n\x12ListenDeliverBlock\x12..cosmos.streaming.v1.ListenDeliverBlockRequest\x1a/.cosmos.streaming.v1.ListenDeliverBlockResponse\x12u\n\x12ListenStateChanges\x12..cosmos.streaming.v1.ListenStateChangesRequest\x1a/.cosmos.streaming.v1.ListenStateChangesResponseB\"Z cosmossdk.io/server/v2/streamingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cosmos.streaming.v1.grpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z cosmossdk.io/server/v2/streaming'
  _globals['_LISTENDELIVERBLOCKREQUEST']._serialized_start=56
  _globals['_LISTENDELIVERBLOCKREQUEST']._serialized_end=217
  _globals['_LISTENDELIVERBLOCKRESPONSE']._serialized_start=219
  _globals['_LISTENDELIVERBLOCKRESPONSE']._serialized_end=247
  _globals['_LISTENSTATECHANGESREQUEST']._serialized_start=249
  _globals['_LISTENSTATECHANGESREQUEST']._serialized_end=370
  _globals['_LISTENSTATECHANGESRESPONSE']._serialized_start=372
  _globals['_LISTENSTATECHANGESRESPONSE']._serialized_end=400
  _globals['_STOREKVPAIR']._serialized_start=402
  _globals['_STOREKVPAIR']._serialized_end=476
  _globals['_EVENT']._serialized_start=478
  _globals['_EVENT']._serialized_end=556
  _globals['_EVENTATTRIBUTE']._serialized_start=558
  _globals['_EVENTATTRIBUTE']._serialized_end=602
  _globals['_EXECTXRESULT']._serialized_start=605
  _globals['_EXECTXRESULT']._serialized_end=775
  _globals['_LISTENERSERVICE']._serialized_start=778
  _globals['_LISTENERSERVICE']._serialized_end=1033
# @@protoc_insertion_point(module_scope)
