# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/conflict/conflict_vote.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/conflict/conflict_vote.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)lavanet/lava/conflict/conflict_vote.proto\x12\x15lavanet.lava.conflict\x1a\x14gogoproto/gogo.proto\"-\n\x08Provider\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\x0c\"5\n\x04Vote\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04Hash\x18\x02 \x01(\x0c\x12\x0e\n\x06Result\x18\x03 \x01(\x03\"\xf0\x02\n\x0c\x43onflictVote\x12\r\n\x05index\x18\x01 \x01(\t\x12\x15\n\rclientAddress\x18\x02 \x01(\t\x12\x14\n\x0cvoteDeadline\x18\x03 \x01(\x04\x12\x16\n\x0evoteStartBlock\x18\x04 \x01(\x04\x12\x11\n\tvoteState\x18\x05 \x01(\x03\x12\x0f\n\x07\x63hainID\x18\x06 \x01(\t\x12\x0e\n\x06\x61piUrl\x18\x07 \x01(\t\x12\x13\n\x0brequestData\x18\x08 \x01(\x0c\x12\x14\n\x0crequestBlock\x18\t \x01(\x04\x12<\n\rfirstProvider\x18\n \x01(\x0b\x32\x1f.lavanet.lava.conflict.ProviderB\x04\xc8\xde\x1f\x00\x12=\n\x0esecondProvider\x18\x0b \x01(\x0b\x32\x1f.lavanet.lava.conflict.ProviderB\x04\xc8\xde\x1f\x00\x12\x30\n\x05votes\x18\x0c \x03(\x0b\x32\x1b.lavanet.lava.conflict.VoteB\x04\xc8\xde\x1f\x00\x42-Z+github.com/lavanet/lava/v2/x/conflict/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.conflict.conflict_vote_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/lavanet/lava/v2/x/conflict/types'
  _globals['_CONFLICTVOTE'].fields_by_name['firstProvider']._loaded_options = None
  _globals['_CONFLICTVOTE'].fields_by_name['firstProvider']._serialized_options = b'\310\336\037\000'
  _globals['_CONFLICTVOTE'].fields_by_name['secondProvider']._loaded_options = None
  _globals['_CONFLICTVOTE'].fields_by_name['secondProvider']._serialized_options = b'\310\336\037\000'
  _globals['_CONFLICTVOTE'].fields_by_name['votes']._loaded_options = None
  _globals['_CONFLICTVOTE'].fields_by_name['votes']._serialized_options = b'\310\336\037\000'
  _globals['_PROVIDER']._serialized_start=90
  _globals['_PROVIDER']._serialized_end=135
  _globals['_VOTE']._serialized_start=137
  _globals['_VOTE']._serialized_end=190
  _globals['_CONFLICTVOTE']._serialized_start=193
  _globals['_CONFLICTVOTE']._serialized_end=561
# @@protoc_insertion_point(module_scope)
