# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/plans/plans_proposal.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/plans/plans_proposal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from lavanet.lava.plans import plan_pb2 as lavanet_dot_lava_dot_plans_dot_plan__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'lavanet/lava/plans/plans_proposal.proto\x12\x12lavanet.lava.plans\x1a\x14gogoproto/gogo.proto\x1a\x1dlavanet/lava/plans/plan.proto\"\xb0\x01\n\x10PlansAddProposal\x12\x18\n\x05title\x18\x01 \x01(\tB\t\xea\xde\x1f\x05title\x12$\n\x0b\x64\x65scription\x18\x02 \x01(\tB\x0f\xea\xde\x1f\x0b\x64\x65scription\x12\x36\n\x05plans\x18\x03 \x03(\x0b\x32\x18.lavanet.lava.plans.PlanB\r\xc8\xde\x1f\x00\xea\xde\x1f\x05plans\x12\x1a\n\x06modify\x18\x04 \x01(\x08\x42\n\xea\xde\x1f\x06modify:\x08\x88\xa0\x1f\x00\x98\xa0\x1f\x00\"v\n\x10PlansDelProposal\x12\x18\n\x05title\x18\x01 \x01(\tB\t\xea\xde\x1f\x05title\x12$\n\x0b\x64\x65scription\x18\x02 \x01(\tB\x0f\xea\xde\x1f\x0b\x64\x65scription\x12\x18\n\x05plans\x18\x03 \x03(\tB\t\xea\xde\x1f\x05plans:\x08\x88\xa0\x1f\x00\x98\xa0\x1f\x00\x42.Z(github.com/lavanet/lava/v2/x/plans/types\xa8\xe2\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.plans.plans_proposal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/lavanet/lava/v2/x/plans/types\250\342\036\001'
  _globals['_PLANSADDPROPOSAL'].fields_by_name['title']._loaded_options = None
  _globals['_PLANSADDPROPOSAL'].fields_by_name['title']._serialized_options = b'\352\336\037\005title'
  _globals['_PLANSADDPROPOSAL'].fields_by_name['description']._loaded_options = None
  _globals['_PLANSADDPROPOSAL'].fields_by_name['description']._serialized_options = b'\352\336\037\013description'
  _globals['_PLANSADDPROPOSAL'].fields_by_name['plans']._loaded_options = None
  _globals['_PLANSADDPROPOSAL'].fields_by_name['plans']._serialized_options = b'\310\336\037\000\352\336\037\005plans'
  _globals['_PLANSADDPROPOSAL'].fields_by_name['modify']._loaded_options = None
  _globals['_PLANSADDPROPOSAL'].fields_by_name['modify']._serialized_options = b'\352\336\037\006modify'
  _globals['_PLANSADDPROPOSAL']._loaded_options = None
  _globals['_PLANSADDPROPOSAL']._serialized_options = b'\210\240\037\000\230\240\037\000'
  _globals['_PLANSDELPROPOSAL'].fields_by_name['title']._loaded_options = None
  _globals['_PLANSDELPROPOSAL'].fields_by_name['title']._serialized_options = b'\352\336\037\005title'
  _globals['_PLANSDELPROPOSAL'].fields_by_name['description']._loaded_options = None
  _globals['_PLANSDELPROPOSAL'].fields_by_name['description']._serialized_options = b'\352\336\037\013description'
  _globals['_PLANSDELPROPOSAL'].fields_by_name['plans']._loaded_options = None
  _globals['_PLANSDELPROPOSAL'].fields_by_name['plans']._serialized_options = b'\352\336\037\005plans'
  _globals['_PLANSDELPROPOSAL']._loaded_options = None
  _globals['_PLANSDELPROPOSAL']._serialized_options = b'\210\240\037\000\230\240\037\000'
  _globals['_PLANSADDPROPOSAL']._serialized_start=117
  _globals['_PLANSADDPROPOSAL']._serialized_end=293
  _globals['_PLANSDELPROPOSAL']._serialized_start=295
  _globals['_PLANSDELPROPOSAL']._serialized_end=413
# @@protoc_insertion_point(module_scope)
