# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/plans/query.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/plans/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from cosmos.base.query.v1beta1 import pagination_pb2 as cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2
from lavanet.lava.plans import params_pb2 as lavanet_dot_lava_dot_plans_dot_params__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from lavanet.lava.plans import plan_pb2 as lavanet_dot_lava_dot_plans_dot_plan__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1elavanet/lava/plans/query.proto\x12\x12lavanet.lava.plans\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x1flavanet/lava/plans/params.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a\x1dlavanet/lava/plans/plan.proto\"\x14\n\x12QueryParamsRequest\"G\n\x13QueryParamsResponse\x12\x30\n\x06params\x18\x01 \x01(\x0b\x32\x1a.lavanet.lava.plans.ParamsB\x04\xc8\xde\x1f\x00\"\x12\n\x10QueryListRequest\"Q\n\x11QueryListResponse\x12<\n\nplans_info\x18\x01 \x03(\x0b\x32\".lavanet.lava.plans.ListInfoStructB\x04\xc8\xde\x1f\x00\"d\n\x0eListInfoStruct\x12\r\n\x05index\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12.\n\x05price\x18\x03 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00\"&\n\x10QueryInfoRequest\x12\x12\n\nplan_index\x18\x01 \x01(\t\"F\n\x11QueryInfoResponse\x12\x31\n\tplan_info\x18\x01 \x01(\x0b\x32\x18.lavanet.lava.plans.PlanB\x04\xc8\xde\x1f\x00\x32\x82\x03\n\x05Query\x12}\n\x06Params\x12&.lavanet.lava.plans.QueryParamsRequest\x1a\'.lavanet.lava.plans.QueryParamsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/lavanet/lava/plans/params\x12u\n\x04List\x12$.lavanet.lava.plans.QueryListRequest\x1a%.lavanet.lava.plans.QueryListResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/lavanet/lava/plans/list\x12\x82\x01\n\x04Info\x12$.lavanet.lava.plans.QueryInfoRequest\x1a%.lavanet.lava.plans.QueryInfoResponse\"-\x82\xd3\xe4\x93\x02\'\x12%/lavanet/lava/plans/info/{plan_index}B*Z(github.com/lavanet/lava/v2/x/plans/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.plans.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/lavanet/lava/v2/x/plans/types'
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._loaded_options = None
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._serialized_options = b'\310\336\037\000'
  _globals['_QUERYLISTRESPONSE'].fields_by_name['plans_info']._loaded_options = None
  _globals['_QUERYLISTRESPONSE'].fields_by_name['plans_info']._serialized_options = b'\310\336\037\000'
  _globals['_LISTINFOSTRUCT'].fields_by_name['price']._loaded_options = None
  _globals['_LISTINFOSTRUCT'].fields_by_name['price']._serialized_options = b'\310\336\037\000'
  _globals['_QUERYINFORESPONSE'].fields_by_name['plan_info']._loaded_options = None
  _globals['_QUERYINFORESPONSE'].fields_by_name['plan_info']._serialized_options = b'\310\336\037\000'
  _globals['_QUERY'].methods_by_name['Params']._loaded_options = None
  _globals['_QUERY'].methods_by_name['Params']._serialized_options = b'\202\323\344\223\002\034\022\032/lavanet/lava/plans/params'
  _globals['_QUERY'].methods_by_name['List']._loaded_options = None
  _globals['_QUERY'].methods_by_name['List']._serialized_options = b'\202\323\344\223\002\032\022\030/lavanet/lava/plans/list'
  _globals['_QUERY'].methods_by_name['Info']._loaded_options = None
  _globals['_QUERY'].methods_by_name['Info']._serialized_options = b'\202\323\344\223\002\'\022%/lavanet/lava/plans/info/{plan_index}'
  _globals['_QUERYPARAMSREQUEST']._serialized_start=246
  _globals['_QUERYPARAMSREQUEST']._serialized_end=266
  _globals['_QUERYPARAMSRESPONSE']._serialized_start=268
  _globals['_QUERYPARAMSRESPONSE']._serialized_end=339
  _globals['_QUERYLISTREQUEST']._serialized_start=341
  _globals['_QUERYLISTREQUEST']._serialized_end=359
  _globals['_QUERYLISTRESPONSE']._serialized_start=361
  _globals['_QUERYLISTRESPONSE']._serialized_end=442
  _globals['_LISTINFOSTRUCT']._serialized_start=444
  _globals['_LISTINFOSTRUCT']._serialized_end=544
  _globals['_QUERYINFOREQUEST']._serialized_start=546
  _globals['_QUERYINFOREQUEST']._serialized_end=584
  _globals['_QUERYINFORESPONSE']._serialized_start=586
  _globals['_QUERYINFORESPONSE']._serialized_end=656
  _globals['_QUERY']._serialized_start=659
  _globals['_QUERY']._serialized_end=1045
# @@protoc_insertion_point(module_scope)
