# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/pairing/unstake_proposal.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/pairing/unstake_proposal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+lavanet/lava/pairing/unstake_proposal.proto\x12\x14lavanet.lava.pairing\x1a\x14gogoproto/gogo.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\"\xcf\x01\n\x0fUnstakeProposal\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12G\n\x0eproviders_info\x18\x03 \x03(\x0b\x32).lavanet.lava.pairing.ProviderUnstakeInfoB\x04\xc8\xde\x1f\x00\x12I\n\x12\x44\x65legatorsSlashing\x18\x04 \x03(\x0b\x32\'.lavanet.lava.pairing.DelegatorSlashingB\x04\xc8\xde\x1f\x00:\x04\x88\xa0\x1f\x00\"9\n\x13ProviderUnstakeInfo\x12\x10\n\x08provider\x18\x01 \x01(\t\x12\x10\n\x08\x63hain_id\x18\x02 \x01(\t\"`\n\x11\x44\x65legatorSlashing\x12\x11\n\tdelegator\x18\x01 \x01(\t\x12\x38\n\x0fslashing_amount\x18\x02 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00\x42,Z*github.com/lavanet/lava/v2/x/pairing/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.pairing.unstake_proposal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/lavanet/lava/v2/x/pairing/types'
  _globals['_UNSTAKEPROPOSAL'].fields_by_name['providers_info']._loaded_options = None
  _globals['_UNSTAKEPROPOSAL'].fields_by_name['providers_info']._serialized_options = b'\310\336\037\000'
  _globals['_UNSTAKEPROPOSAL'].fields_by_name['DelegatorsSlashing']._loaded_options = None
  _globals['_UNSTAKEPROPOSAL'].fields_by_name['DelegatorsSlashing']._serialized_options = b'\310\336\037\000'
  _globals['_UNSTAKEPROPOSAL']._loaded_options = None
  _globals['_UNSTAKEPROPOSAL']._serialized_options = b'\210\240\037\000'
  _globals['_DELEGATORSLASHING'].fields_by_name['slashing_amount']._loaded_options = None
  _globals['_DELEGATORSLASHING'].fields_by_name['slashing_amount']._serialized_options = b'\310\336\037\000'
  _globals['_UNSTAKEPROPOSAL']._serialized_start=156
  _globals['_UNSTAKEPROPOSAL']._serialized_end=363
  _globals['_PROVIDERUNSTAKEINFO']._serialized_start=365
  _globals['_PROVIDERUNSTAKEINFO']._serialized_end=422
  _globals['_DELEGATORSLASHING']._serialized_start=424
  _globals['_DELEGATORSLASHING']._serialized_end=520
# @@protoc_insertion_point(module_scope)
