# Generated by Django 4.2.16 on 2024-09-04 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveBigIntegerField()),
                ('reward_amount', models.PositiveIntegerField()),
                ('reward_type', models.CharField(choices=[('Manual', 'Manual'), ('OnChain', 'Onchain')], max_length=16)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchains.chain')),
            ],
        ),
    ]
