# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/plans/genesis.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/plans/genesis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from lavanet.lava.plans import params_pb2 as lavanet_dot_lava_dot_plans_dot_params__pb2
from lavanet.lava.fixationstore import fixation_pb2 as lavanet_dot_lava_dot_fixationstore_dot_fixation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n lavanet/lava/plans/genesis.proto\x12\x12lavanet.lava.plans\x1a\x14gogoproto/gogo.proto\x1a\x1flavanet/lava/plans/params.proto\x1a)lavanet/lava/fixationstore/fixation.proto\"\x81\x01\n\x0cGenesisState\x12\x30\n\x06params\x18\x01 \x01(\x0b\x32\x1a.lavanet.lava.plans.ParamsB\x04\xc8\xde\x1f\x00\x12?\n\x07plansFS\x18\x02 \x01(\x0b\x32(.lavanet.lava.fixationstore.GenesisStateB\x04\xc8\xde\x1f\x00\x42*Z(github.com/lavanet/lava/v2/x/plans/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.plans.genesis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/lavanet/lava/v2/x/plans/types'
  _globals['_GENESISSTATE'].fields_by_name['params']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['params']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['plansFS']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['plansFS']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE']._serialized_start=155
  _globals['_GENESISSTATE']._serialized_end=284
# @@protoc_insertion_point(module_scope)
