# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/plans/policy.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/plans/policy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from lavanet.lava.spec import api_collection_pb2 as lavanet_dot_lava_dot_spec_dot_api__collection__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1flavanet/lava/plans/policy.proto\x12\x12lavanet.lava.plans\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a&lavanet/lava/spec/api_collection.proto\"\xc0\x03\n\x06Policy\x12O\n\x0e\x63hain_policies\x18\x01 \x03(\x0b\x32\x1f.lavanet.lava.plans.ChainPolicyB\x16\xc8\xde\x1f\x00\xea\xde\x1f\x0e\x63hain_policies\x12\x34\n\x13geolocation_profile\x18\x02 \x01(\x05\x42\x17\xea\xde\x1f\x13geolocation_profile\x12*\n\x0etotal_cu_limit\x18\x03 \x01(\x04\x42\x12\xea\xde\x1f\x0etotal_cu_limit\x12*\n\x0e\x65poch_cu_limit\x18\x04 \x01(\x04\x42\x12\xea\xde\x1f\x0e\x65poch_cu_limit\x12\x38\n\x15max_providers_to_pair\x18\x05 \x01(\x04\x42\x19\xea\xde\x1f\x15max_providers_to_pair\x12i\n\x17selected_providers_mode\x18\x06 \x01(\x0e\x32+.lavanet.lava.plans.SELECTED_PROVIDERS_MODEB\x1b\xea\xde\x1f\x17selected_providers_mode\x12\x32\n\x12selected_providers\x18\x07 \x03(\tB\x16\xea\xde\x1f\x12selected_providers\"\x97\x01\n\x0b\x43hainPolicy\x12\x1e\n\x08\x63hain_id\x18\x01 \x01(\tB\x0c\xea\xde\x1f\x08\x63hain_id\x12\x16\n\x04\x61pis\x18\x02 \x03(\tB\x08\xea\xde\x1f\x04\x61pis\x12P\n\x0crequirements\x18\x03 \x03(\x0b\x32$.lavanet.lava.plans.ChainRequirementB\x14\xc8\xde\x1f\x00\xea\xde\x1f\x0crequirements\"\x9b\x01\n\x10\x43hainRequirement\x12I\n\ncollection\x18\x01 \x01(\x0b\x32!.lavanet.lava.spec.CollectionDataB\x12\xc8\xde\x1f\x00\xea\xde\x1f\ncollection\x12\"\n\nextensions\x18\x02 \x03(\tB\x0e\xea\xde\x1f\nextensions\x12\x18\n\x05mixed\x18\x03 \x01(\x08\x42\t\xea\xde\x1f\x05mixed*N\n\x17SELECTED_PROVIDERS_MODE\x12\x0b\n\x07\x41LLOWED\x10\x00\x12\t\n\x05MIXED\x10\x01\x12\r\n\tEXCLUSIVE\x10\x02\x12\x0c\n\x08\x44ISABLED\x10\x03\x42.Z(github.com/lavanet/lava/v2/x/plans/types\xa8\xe2\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.plans.policy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/lavanet/lava/v2/x/plans/types\250\342\036\001'
  _globals['_POLICY'].fields_by_name['chain_policies']._loaded_options = None
  _globals['_POLICY'].fields_by_name['chain_policies']._serialized_options = b'\310\336\037\000\352\336\037\016chain_policies'
  _globals['_POLICY'].fields_by_name['geolocation_profile']._loaded_options = None
  _globals['_POLICY'].fields_by_name['geolocation_profile']._serialized_options = b'\352\336\037\023geolocation_profile'
  _globals['_POLICY'].fields_by_name['total_cu_limit']._loaded_options = None
  _globals['_POLICY'].fields_by_name['total_cu_limit']._serialized_options = b'\352\336\037\016total_cu_limit'
  _globals['_POLICY'].fields_by_name['epoch_cu_limit']._loaded_options = None
  _globals['_POLICY'].fields_by_name['epoch_cu_limit']._serialized_options = b'\352\336\037\016epoch_cu_limit'
  _globals['_POLICY'].fields_by_name['max_providers_to_pair']._loaded_options = None
  _globals['_POLICY'].fields_by_name['max_providers_to_pair']._serialized_options = b'\352\336\037\025max_providers_to_pair'
  _globals['_POLICY'].fields_by_name['selected_providers_mode']._loaded_options = None
  _globals['_POLICY'].fields_by_name['selected_providers_mode']._serialized_options = b'\352\336\037\027selected_providers_mode'
  _globals['_POLICY'].fields_by_name['selected_providers']._loaded_options = None
  _globals['_POLICY'].fields_by_name['selected_providers']._serialized_options = b'\352\336\037\022selected_providers'
  _globals['_CHAINPOLICY'].fields_by_name['chain_id']._loaded_options = None
  _globals['_CHAINPOLICY'].fields_by_name['chain_id']._serialized_options = b'\352\336\037\010chain_id'
  _globals['_CHAINPOLICY'].fields_by_name['apis']._loaded_options = None
  _globals['_CHAINPOLICY'].fields_by_name['apis']._serialized_options = b'\352\336\037\004apis'
  _globals['_CHAINPOLICY'].fields_by_name['requirements']._loaded_options = None
  _globals['_CHAINPOLICY'].fields_by_name['requirements']._serialized_options = b'\310\336\037\000\352\336\037\014requirements'
  _globals['_CHAINREQUIREMENT'].fields_by_name['collection']._loaded_options = None
  _globals['_CHAINREQUIREMENT'].fields_by_name['collection']._serialized_options = b'\310\336\037\000\352\336\037\ncollection'
  _globals['_CHAINREQUIREMENT'].fields_by_name['extensions']._loaded_options = None
  _globals['_CHAINREQUIREMENT'].fields_by_name['extensions']._serialized_options = b'\352\336\037\nextensions'
  _globals['_CHAINREQUIREMENT'].fields_by_name['mixed']._loaded_options = None
  _globals['_CHAINREQUIREMENT'].fields_by_name['mixed']._serialized_options = b'\352\336\037\005mixed'
  _globals['_SELECTED_PROVIDERS_MODE']._serialized_start=912
  _globals['_SELECTED_PROVIDERS_MODE']._serialized_end=990
  _globals['_POLICY']._serialized_start=150
  _globals['_POLICY']._serialized_end=598
  _globals['_CHAINPOLICY']._serialized_start=601
  _globals['_CHAINPOLICY']._serialized_end=752
  _globals['_CHAINREQUIREMENT']._serialized_start=755
  _globals['_CHAINREQUIREMENT']._serialized_end=910
# @@protoc_insertion_point(module_scope)
