# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/conflict/conflict_data.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/conflict/conflict_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from lavanet.lava.pairing import relay_pb2 as lavanet_dot_lava_dot_pairing_dot_relay__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)lavanet/lava/conflict/conflict_data.proto\x12\x15lavanet.lava.conflict\x1a\x14gogoproto/gogo.proto\x1a lavanet/lava/pairing/relay.proto\"\x9e\x01\n\x10ResponseConflict\x12\x44\n\x12\x63onflictRelayData0\x18\x01 \x01(\x0b\x32(.lavanet.lava.conflict.ConflictRelayData\x12\x44\n\x12\x63onflictRelayData1\x18\x02 \x01(\x0b\x32(.lavanet.lava.conflict.ConflictRelayData\"\x83\x01\n\x11\x43onflictRelayData\x12\x33\n\x07request\x18\x01 \x01(\x0b\x32\".lavanet.lava.pairing.RelayRequest\x12\x33\n\x05reply\x18\x03 \x01(\x0b\x32$.lavanet.lava.conflict.ReplyMetadataJ\x04\x08\x02\x10\x03\"\x83\x01\n\rReplyMetadata\x12\x1a\n\x12hash_all_data_hash\x18\x01 \x01(\x0c\x12\x0b\n\x03sig\x18\x02 \x01(\x0c\x12\x14\n\x0clatest_block\x18\x03 \x01(\x03\x12\x1f\n\x17\x66inalized_blocks_hashes\x18\x04 \x01(\x0c\x12\x12\n\nsig_blocks\x18\x05 \x01(\x0c\"\xa6\x01\n\x14\x46inalizationConflict\x12\x46\n\x14relay_finalization_0\x18\x01 \x01(\x0b\x32(.lavanet.lava.conflict.RelayFinalization\x12\x46\n\x14relay_finalization_1\x18\x02 \x01(\x0b\x32(.lavanet.lava.conflict.RelayFinalization\"\xb3\x01\n\x11RelayFinalization\x12\x1f\n\x17\x66inalized_blocks_hashes\x18\x01 \x01(\x0c\x12\x14\n\x0clatest_block\x18\x02 \x01(\x03\x12\x18\n\x10\x63onsumer_address\x18\x03 \x01(\t\x12\x39\n\rrelay_session\x18\x04 \x01(\x0b\x32\".lavanet.lava.pairing.RelaySession\x12\x12\n\nsig_blocks\x18\x05 \x01(\x0c\x42-Z+github.com/lavanet/lava/v2/x/conflict/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.conflict.conflict_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/lavanet/lava/v2/x/conflict/types'
  _globals['_RESPONSECONFLICT']._serialized_start=125
  _globals['_RESPONSECONFLICT']._serialized_end=283
  _globals['_CONFLICTRELAYDATA']._serialized_start=286
  _globals['_CONFLICTRELAYDATA']._serialized_end=417
  _globals['_REPLYMETADATA']._serialized_start=420
  _globals['_REPLYMETADATA']._serialized_end=551
  _globals['_FINALIZATIONCONFLICT']._serialized_start=554
  _globals['_FINALIZATIONCONFLICT']._serialized_end=720
  _globals['_RELAYFINALIZATION']._serialized_start=723
  _globals['_RELAYFINALIZATION']._serialized_end=902
# @@protoc_insertion_point(module_scope)
