# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/conflict/params.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/conflict/params.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"lavanet/lava/conflict/params.proto\x12\x15lavanet.lava.conflict\x1a\x14gogoproto/gogo.proto\"\xd4\x01\n\x06Params\x12\x62\n\x0fmajorityPercent\x18\x01 \x01(\tBI\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xf2\xde\x1f\x17yaml:\"majority_percent\"\x12\x15\n\rvoteStartSpan\x18\x02 \x01(\x04\x12\x12\n\nvotePeriod\x18\x03 \x01(\x04\x12\x35\n\x07Rewards\x18\x04 \x01(\x0b\x32\x1e.lavanet.lava.conflict.RewardsB\x04\xc8\xde\x1f\x00:\x04\x98\xa0\x1f\x00\"\xd0\x02\n\x07Rewards\x12k\n\x13winnerRewardPercent\x18\x01 \x01(\tBN\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xf2\xde\x1f\x1cyaml:\"winner_reward_percent\"\x12k\n\x13\x63lientRewardPercent\x18\x02 \x01(\tBN\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xf2\xde\x1f\x1cyaml:\"client_reward_percent\"\x12k\n\x13votersRewardPercent\x18\x03 \x01(\tBN\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xf2\xde\x1f\x1cyaml:\"voters_reward_percent\"B-Z+github.com/lavanet/lava/v2/x/conflict/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.conflict.params_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/lavanet/lava/v2/x/conflict/types'
  _globals['_PARAMS'].fields_by_name['majorityPercent']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['majorityPercent']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\362\336\037\027yaml:\"majority_percent\"'
  _globals['_PARAMS'].fields_by_name['Rewards']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['Rewards']._serialized_options = b'\310\336\037\000'
  _globals['_PARAMS']._loaded_options = None
  _globals['_PARAMS']._serialized_options = b'\230\240\037\000'
  _globals['_REWARDS'].fields_by_name['winnerRewardPercent']._loaded_options = None
  _globals['_REWARDS'].fields_by_name['winnerRewardPercent']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\362\336\037\034yaml:\"winner_reward_percent\"'
  _globals['_REWARDS'].fields_by_name['clientRewardPercent']._loaded_options = None
  _globals['_REWARDS'].fields_by_name['clientRewardPercent']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\362\336\037\034yaml:\"client_reward_percent\"'
  _globals['_REWARDS'].fields_by_name['votersRewardPercent']._loaded_options = None
  _globals['_REWARDS'].fields_by_name['votersRewardPercent']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\362\336\037\034yaml:\"voters_reward_percent\"'
  _globals['_PARAMS']._serialized_start=84
  _globals['_PARAMS']._serialized_end=296
  _globals['_REWARDS']._serialized_start=299
  _globals['_REWARDS']._serialized_end=635
# @@protoc_insertion_point(module_scope)
