# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/conflict/tx.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/conflict/tx.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from lavanet.lava.conflict import conflict_data_pb2 as lavanet_dot_lava_dot_conflict_dot_conflict__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1elavanet/lava/conflict/tx.proto\x12\x15lavanet.lava.conflict\x1a\x11\x61mino/amino.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a\x14gogoproto/gogo.proto\x1a)lavanet/lava/conflict/conflict_data.proto\"\xea\x01\n\x0cMsgDetection\x12\x0f\n\x07\x63reator\x18\x01 \x01(\t\x12L\n\x15\x66inalization_conflict\x18\x05 \x01(\x0b\x32+.lavanet.lava.conflict.FinalizationConflictH\x00\x12\x44\n\x11response_conflict\x18\x06 \x01(\x0b\x32\'.lavanet.lava.conflict.ResponseConflictH\x00:\x17\x8a\xe7\xb0*\x12\x63onflict/DetectionB\n\n\x08\x63onflictJ\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05\"\x16\n\x14MsgDetectionResponse\"h\n\x15MsgConflictVoteCommit\x12\x0f\n\x07\x63reator\x18\x01 \x01(\t\x12\x0e\n\x06voteID\x18\x02 \x01(\t\x12\x0c\n\x04hash\x18\x03 \x01(\x0c: \x8a\xe7\xb0*\x1b\x63onflict/ConflictVoteCommit\"\x1f\n\x1dMsgConflictVoteCommitResponse\"w\n\x15MsgConflictVoteReveal\x12\x0f\n\x07\x63reator\x18\x01 \x01(\t\x12\x0e\n\x06voteID\x18\x02 \x01(\t\x12\r\n\x05nonce\x18\x03 \x01(\x03\x12\x0c\n\x04hash\x18\x04 \x01(\x0c: \x8a\xe7\xb0*\x1b\x63onflict/ConflictVoteReveal\"\x1f\n\x1dMsgConflictVoteRevealResponse2\xd8\x02\n\x03Msg\x12]\n\tDetection\x12#.lavanet.lava.conflict.MsgDetection\x1a+.lavanet.lava.conflict.MsgDetectionResponse\x12x\n\x12\x43onflictVoteCommit\x12,.lavanet.lava.conflict.MsgConflictVoteCommit\x1a\x34.lavanet.lava.conflict.MsgConflictVoteCommitResponse\x12x\n\x12\x43onflictVoteReveal\x12,.lavanet.lava.conflict.MsgConflictVoteReveal\x1a\x34.lavanet.lava.conflict.MsgConflictVoteRevealResponseB-Z+github.com/lavanet/lava/v2/x/conflict/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.conflict.tx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/lavanet/lava/v2/x/conflict/types'
  _globals['_MSGDETECTION']._loaded_options = None
  _globals['_MSGDETECTION']._serialized_options = b'\212\347\260*\022conflict/Detection'
  _globals['_MSGCONFLICTVOTECOMMIT']._loaded_options = None
  _globals['_MSGCONFLICTVOTECOMMIT']._serialized_options = b'\212\347\260*\033conflict/ConflictVoteCommit'
  _globals['_MSGCONFLICTVOTEREVEAL']._loaded_options = None
  _globals['_MSGCONFLICTVOTEREVEAL']._serialized_options = b'\212\347\260*\033conflict/ConflictVoteReveal'
  _globals['_MSGDETECTION']._serialized_start=174
  _globals['_MSGDETECTION']._serialized_end=408
  _globals['_MSGDETECTIONRESPONSE']._serialized_start=410
  _globals['_MSGDETECTIONRESPONSE']._serialized_end=432
  _globals['_MSGCONFLICTVOTECOMMIT']._serialized_start=434
  _globals['_MSGCONFLICTVOTECOMMIT']._serialized_end=538
  _globals['_MSGCONFLICTVOTECOMMITRESPONSE']._serialized_start=540
  _globals['_MSGCONFLICTVOTECOMMITRESPONSE']._serialized_end=571
  _globals['_MSGCONFLICTVOTEREVEAL']._serialized_start=573
  _globals['_MSGCONFLICTVOTEREVEAL']._serialized_end=692
  _globals['_MSGCONFLICTVOTEREVEALRESPONSE']._serialized_start=694
  _globals['_MSGCONFLICTVOTEREVEALRESPONSE']._serialized_end=725
  _globals['_MSG']._serialized_start=728
  _globals['_MSG']._serialized_end=1072
# @@protoc_insertion_point(module_scope)
