# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/epochstorage/fixated_params.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/epochstorage/fixated_params.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from lavanet.lava.epochstorage import params_pb2 as lavanet_dot_lava_dot_epochstorage_dot_params__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.lavanet/lava/epochstorage/fixated_params.proto\x12\x19lavanet.lava.epochstorage\x1a\x14gogoproto/gogo.proto\x1a&lavanet/lava/epochstorage/params.proto\"H\n\rFixatedParams\x12\r\n\x05index\x18\x01 \x01(\t\x12\x11\n\tparameter\x18\x02 \x01(\x0c\x12\x15\n\rfixationBlock\x18\x03 \x01(\x04\x42\x31Z/github.com/lavanet/lava/v2/x/epochstorage/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.epochstorage.fixated_params_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/lavanet/lava/v2/x/epochstorage/types'
  _globals['_FIXATEDPARAMS']._serialized_start=139
  _globals['_FIXATEDPARAMS']._serialized_end=211
# @@protoc_insertion_point(module_scope)
