# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-05-15 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsent',
            name='subject',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Subject'),
        ),
    ]
