# Generated by Django 4.2.15 on 2024-08-19 14:04

from django.db import migrations, models
import libs.auth_user.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=libs.auth_user.models.LCaseEmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lang',
            field=models.CharField(choices=[('en', 'English')], default='en', max_length=8, verbose_name='Email Language'),
        ),
    ]
