services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:16.4-alpine3.20
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev

volumes:
  postgres_data:
  static_volume:
  media_volume:
