# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/pairing/account_info.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/pairing/account_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from lavanet.lava.epochstorage import stake_entry_pb2 as lavanet_dot_lava_dot_epochstorage_dot_stake__entry__pb2
from lavanet.lava.dualstaking import delegate_pb2 as lavanet_dot_lava_dot_dualstaking_dot_delegate__pb2
from cosmos.staking.v1beta1 import staking_pb2 as cosmos_dot_staking_dot_v1beta1_dot_staking__pb2
from lavanet.lava.subscription import subscription_pb2 as lavanet_dot_lava_dot_subscription_dot_subscription__pb2
from lavanet.lava.projects import project_pb2 as lavanet_dot_lava_dot_projects_dot_project__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'lavanet/lava/pairing/account_info.proto\x12\x14lavanet.lava.pairing\x1a\x14gogoproto/gogo.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a+lavanet/lava/epochstorage/stake_entry.proto\x1a\'lavanet/lava/dualstaking/delegate.proto\x1a$cosmos/staking/v1beta1/staking.proto\x1a,lavanet/lava/subscription/subscription.proto\x1a#lavanet/lava/projects/project.proto\"\x89\x04\n\x18QueryAccountInfoResponse\x12=\n\x08provider\x18\x01 \x03(\x0b\x32%.lavanet.lava.epochstorage.StakeEntryB\x04\xc8\xde\x1f\x00\x12;\n\x06\x66rozen\x18\x02 \x03(\x0b\x32%.lavanet.lava.epochstorage.StakeEntryB\x04\xc8\xde\x1f\x00\x12=\n\x08unstaked\x18\x04 \x03(\x0b\x32%.lavanet.lava.epochstorage.StakeEntryB\x04\xc8\xde\x1f\x00\x12\x43\n\x0csubscription\x18\x05 \x01(\x0b\x32\'.lavanet.lava.subscription.SubscriptionB\x04\xc8\xde\x1f\x01\x12\x35\n\x07project\x18\x06 \x01(\x0b\x32\x1e.lavanet.lava.projects.ProjectB\x04\xc8\xde\x1f\x01\x12P\n\x16\x64\x65legations_validators\x18\x07 \x03(\x0b\x32*.cosmos.staking.v1beta1.DelegationResponseB\x04\xc8\xde\x1f\x00\x12I\n\x15\x64\x65legations_providers\x18\x08 \x03(\x0b\x32$.lavanet.lava.dualstaking.DelegationB\x04\xc8\xde\x1f\x00\x12\x19\n\x11total_delegations\x18\t \x01(\x04\x42,Z*github.com/lavanet/lava/v2/x/pairing/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.pairing.account_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/lavanet/lava/v2/x/pairing/types'
  _globals['_QUERYACCOUNTINFORESPONSE'].fields_by_name['provider']._loaded_options = None
  _globals['_QUERYACCOUNTINFORESPONSE'].fields_by_name['provider']._serialized_options = b'\310\336\037\000'
  _globals['_QUERYACCOUNTINFORESPONSE'].fields_by_name['frozen']._loaded_options = None
  _globals['_QUERYACCOUNTINFORESPONSE'].fields_by_name['frozen']._serialized_options = b'\310\336\037\000'
  _globals['_QUERYACCOUNTINFORESPONSE'].fields_by_name['unstaked']._loaded_options = None
  _globals['_QUERYACCOUNTINFORESPONSE'].fields_by_name['unstaked']._serialized_options = b'\310\336\037\000'
  _globals['_QUERYACCOUNTINFORESPONSE'].fields_by_name['subscription']._loaded_options = None
  _globals['_QUERYACCOUNTINFORESPONSE'].fields_by_name['subscription']._serialized_options = b'\310\336\037\001'
  _globals['_QUERYACCOUNTINFORESPONSE'].fields_by_name['project']._loaded_options = None
  _globals['_QUERYACCOUNTINFORESPONSE'].fields_by_name['project']._serialized_options = b'\310\336\037\001'
  _globals['_QUERYACCOUNTINFORESPONSE'].fields_by_name['delegations_validators']._loaded_options = None
  _globals['_QUERYACCOUNTINFORESPONSE'].fields_by_name['delegations_validators']._serialized_options = b'\310\336\037\000'
  _globals['_QUERYACCOUNTINFORESPONSE'].fields_by_name['delegations_providers']._loaded_options = None
  _globals['_QUERYACCOUNTINFORESPONSE'].fields_by_name['delegations_providers']._serialized_options = b'\310\336\037\000'
  _globals['_QUERYACCOUNTINFORESPONSE']._serialized_start=327
  _globals['_QUERYACCOUNTINFORESPONSE']._serialized_end=848
# @@protoc_insertion_point(module_scope)
