# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cosmos/consensus/v1/consensus.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'cosmos/consensus/v1/consensus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cometbft.types.v1 import params_pb2 as cometbft_dot_types_dot_v1_dot_params__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#cosmos/consensus/v1/consensus.proto\x12\x13\x63osmos.consensus.v1\x1a\x1e\x63ometbft/types/v1/params.proto\"\xfd\x02\n\x12\x43onsensusMsgParams\x12\x31\n\x07version\x18\x01 \x01(\x0b\x32 .cometbft.types.v1.VersionParams\x12-\n\x05\x62lock\x18\x02 \x01(\x0b\x32\x1e.cometbft.types.v1.BlockParams\x12\x33\n\x08\x65vidence\x18\x03 \x01(\x0b\x32!.cometbft.types.v1.EvidenceParams\x12\x35\n\tvalidator\x18\x04 \x01(\x0b\x32\".cometbft.types.v1.ValidatorParams\x12/\n\x04\x61\x62\x63i\x18\x05 \x01(\x0b\x32\x1d.cometbft.types.v1.ABCIParamsB\x02\x18\x01\x12\x35\n\tsynchrony\x18\x06 \x01(\x0b\x32\".cometbft.types.v1.SynchronyParams\x12\x31\n\x07\x66\x65\x61ture\x18\x07 \x01(\x0b\x32 .cometbft.types.v1.FeatureParams\"\x1c\n\x1a\x43onsensusMsgParamsResponseB Z\x1e\x63osmossdk.io/x/consensus/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cosmos.consensus.v1.consensus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\036cosmossdk.io/x/consensus/types'
  _globals['_CONSENSUSMSGPARAMS'].fields_by_name['abci']._loaded_options = None
  _globals['_CONSENSUSMSGPARAMS'].fields_by_name['abci']._serialized_options = b'\030\001'
  _globals['_CONSENSUSMSGPARAMS']._serialized_start=93
  _globals['_CONSENSUSMSGPARAMS']._serialized_end=474
  _globals['_CONSENSUSMSGPARAMSRESPONSE']._serialized_start=476
  _globals['_CONSENSUSMSGPARAMSRESPONSE']._serialized_end=504
# @@protoc_insertion_point(module_scope)
