# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/timerstore/timer.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/timerstore/timer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#lavanet/lava/timerstore/timer.proto\x12\x17lavanet.lava.timerstore\x1a\x14gogoproto/gogo.proto\"\xe4\x01\n\x0cGenesisState\x12\x0f\n\x07version\x18\x01 \x01(\x04\x12\x19\n\x11next_block_height\x18\x02 \x01(\x04\x12\x17\n\x0fnext_block_time\x18\x03 \x01(\x04\x12\x46\n\x0ctime_entries\x18\x04 \x03(\x0b\x32*.lavanet.lava.timerstore.GenesisTimerEntryB\x04\xc8\xde\x1f\x00\x12G\n\rblock_entries\x18\x05 \x03(\x0b\x32*.lavanet.lava.timerstore.GenesisTimerEntryB\x04\xc8\xde\x1f\x00\"=\n\x11GenesisTimerEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x42/Z-github.com/lavanet/lava/v2/x/timerstore/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.timerstore.timer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-github.com/lavanet/lava/v2/x/timerstore/types'
  _globals['_GENESISSTATE'].fields_by_name['time_entries']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['time_entries']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['block_entries']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['block_entries']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE']._serialized_start=87
  _globals['_GENESISSTATE']._serialized_end=315
  _globals['_GENESISTIMERENTRY']._serialized_start=317
  _globals['_GENESISTIMERENTRY']._serialized_end=378
# @@protoc_insertion_point(module_scope)
