# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/protocol/tx.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/protocol/tx.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from lavanet.lava.protocol import params_pb2 as lavanet_dot_lava_dot_protocol_dot_params__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1elavanet/lava/protocol/tx.proto\x12\x15lavanet.lava.protocol\x1a\x11\x61mino/amino.proto\x1a\"lavanet/lava/protocol/params.proto\"p\n\rMsgSetVersion\x12\x11\n\tauthority\x18\x01 \x01(\t\x12/\n\x07version\x18\x02 \x01(\x0b\x32\x1e.lavanet.lava.protocol.Version:\x1b\x8a\xe7\xb0*\x16protocol/MsgSetVersion\"\x17\n\x15MsgSetVersionResponse2g\n\x03Msg\x12`\n\nSetVersion\x12$.lavanet.lava.protocol.MsgSetVersion\x1a,.lavanet.lava.protocol.MsgSetVersionResponseB-Z+github.com/lavanet/lava/v2/x/protocol/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.protocol.tx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/lavanet/lava/v2/x/protocol/types'
  _globals['_MSGSETVERSION']._loaded_options = None
  _globals['_MSGSETVERSION']._serialized_options = b'\212\347\260*\026protocol/MsgSetVersion'
  _globals['_MSGSETVERSION']._serialized_start=112
  _globals['_MSGSETVERSION']._serialized_end=224
  _globals['_MSGSETVERSIONRESPONSE']._serialized_start=226
  _globals['_MSGSETVERSIONRESPONSE']._serialized_end=249
  _globals['_MSG']._serialized_start=251
  _globals['_MSG']._serialized_end=354
# @@protoc_insertion_point(module_scope)
