# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/projects/project.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/projects/project.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from lavanet.lava.plans import policy_pb2 as lavanet_dot_lava_dot_plans_dot_policy__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#lavanet/lava/projects/project.proto\x12\x15lavanet.lava.projects\x1a\x14gogoproto/gogo.proto\x1a\x1flavanet/lava/plans/policy.proto\"\xcd\x02\n\x07Project\x12\r\n\x05index\x18\x01 \x01(\t\x12\x14\n\x0csubscription\x18\x02 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x04 \x01(\x08\x12M\n\x0cproject_keys\x18\x05 \x03(\x0b\x32!.lavanet.lava.projects.ProjectKeyB\x14\xc8\xde\x1f\x00\xea\xde\x1f\x0cproject_keys\x12\x42\n\x0c\x61\x64min_policy\x18\x06 \x01(\x0b\x32\x1a.lavanet.lava.plans.PolicyB\x10\xea\xde\x1f\x0c\x61\x64min_policy\x12\x0f\n\x07used_cu\x18\x07 \x01(\x04\x12P\n\x13subscription_policy\x18\x08 \x01(\x0b\x32\x1a.lavanet.lava.plans.PolicyB\x17\xea\xde\x1f\x13subscription_policy\x12\x10\n\x08snapshot\x18\t \x01(\x04J\x04\x08\x03\x10\x04\"t\n\nProjectKey\x12\x14\n\x03key\x18\x01 \x01(\tB\x07\xea\xde\x1f\x03key\x12\x18\n\x05kinds\x18\x04 \x01(\rB\t\xea\xde\x1f\x05kinds\"*\n\x04Type\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05\x41\x44MIN\x10\x01\x12\r\n\tDEVELOPER\x10\x02J\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04\"-\n\x12ProtoDeveloperData\x12\x11\n\tprojectID\x18\x01 \x01(\tJ\x04\x08\x02\x10\x03\"\x9c\x01\n\x0bProjectData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x03 \x01(\x08\x12<\n\x0bprojectKeys\x18\x04 \x03(\x0b\x32!.lavanet.lava.projects.ProjectKeyB\x04\xc8\xde\x1f\x00\x12*\n\x06policy\x18\x05 \x01(\x0b\x32\x1a.lavanet.lava.plans.PolicyJ\x04\x08\x02\x10\x03\x42\x31Z+github.com/lavanet/lava/v2/x/projects/types\xa8\xe2\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.projects.project_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/lavanet/lava/v2/x/projects/types\250\342\036\001'
  _globals['_PROJECT'].fields_by_name['project_keys']._loaded_options = None
  _globals['_PROJECT'].fields_by_name['project_keys']._serialized_options = b'\310\336\037\000\352\336\037\014project_keys'
  _globals['_PROJECT'].fields_by_name['admin_policy']._loaded_options = None
  _globals['_PROJECT'].fields_by_name['admin_policy']._serialized_options = b'\352\336\037\014admin_policy'
  _globals['_PROJECT'].fields_by_name['subscription_policy']._loaded_options = None
  _globals['_PROJECT'].fields_by_name['subscription_policy']._serialized_options = b'\352\336\037\023subscription_policy'
  _globals['_PROJECTKEY'].fields_by_name['key']._loaded_options = None
  _globals['_PROJECTKEY'].fields_by_name['key']._serialized_options = b'\352\336\037\003key'
  _globals['_PROJECTKEY'].fields_by_name['kinds']._loaded_options = None
  _globals['_PROJECTKEY'].fields_by_name['kinds']._serialized_options = b'\352\336\037\005kinds'
  _globals['_PROJECTDATA'].fields_by_name['projectKeys']._loaded_options = None
  _globals['_PROJECTDATA'].fields_by_name['projectKeys']._serialized_options = b'\310\336\037\000'
  _globals['_PROJECT']._serialized_start=118
  _globals['_PROJECT']._serialized_end=451
  _globals['_PROJECTKEY']._serialized_start=453
  _globals['_PROJECTKEY']._serialized_end=569
  _globals['_PROJECTKEY_TYPE']._serialized_start=515
  _globals['_PROJECTKEY_TYPE']._serialized_end=557
  _globals['_PROTODEVELOPERDATA']._serialized_start=571
  _globals['_PROTODEVELOPERDATA']._serialized_end=616
  _globals['_PROJECTDATA']._serialized_start=619
  _globals['_PROJECTDATA']._serialized_end=775
# @@protoc_insertion_point(module_scope)
