# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/projects/query.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/projects/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from lavanet.lava.projects import params_pb2 as lavanet_dot_lava_dot_projects_dot_params__pb2
from lavanet.lava.projects import project_pb2 as lavanet_dot_lava_dot_projects_dot_project__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!lavanet/lava/projects/query.proto\x12\x15lavanet.lava.projects\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\x1a\"lavanet/lava/projects/params.proto\x1a#lavanet/lava/projects/project.proto\"\x14\n\x12QueryParamsRequest\"J\n\x13QueryParamsResponse\x12\x33\n\x06params\x18\x01 \x01(\x0b\x32\x1d.lavanet.lava.projects.ParamsB\x04\xc8\xde\x1f\x00\"#\n\x10QueryInfoRequest\x12\x0f\n\x07project\x18\x01 \x01(\t\"}\n\x11QueryInfoResponse\x12/\n\x07project\x18\x01 \x01(\x0b\x32\x1e.lavanet.lava.projects.Project\x12\x37\n\x0fpending_project\x18\x02 \x01(\x0b\x32\x1e.lavanet.lava.projects.Project\"*\n\x15QueryDeveloperRequest\x12\x11\n\tdeveloper\x18\x01 \x01(\t\"\x82\x01\n\x16QueryDeveloperResponse\x12/\n\x07project\x18\x01 \x01(\x0b\x32\x1e.lavanet.lava.projects.Project\x12\x37\n\x0fpending_project\x18\x02 \x01(\x0b\x32\x1e.lavanet.lava.projects.Project2\xbc\x03\n\x05Query\x12\x86\x01\n\x06Params\x12).lavanet.lava.projects.QueryParamsRequest\x1a*.lavanet.lava.projects.QueryParamsResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/lavanet/lava/projects/params\x12\x88\x01\n\x04Info\x12\'.lavanet.lava.projects.QueryInfoRequest\x1a(.lavanet.lava.projects.QueryInfoResponse\"-\x82\xd3\xe4\x93\x02\'\x12%/lavanet/lava/projects/info/{project}\x12\x9e\x01\n\tDeveloper\x12,.lavanet.lava.projects.QueryDeveloperRequest\x1a-.lavanet.lava.projects.QueryDeveloperResponse\"4\x82\xd3\xe4\x93\x02.\x12,/lavanet/lava/projects/developer/{developer}B-Z+github.com/lavanet/lava/v2/x/projects/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.projects.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/lavanet/lava/v2/x/projects/types'
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._loaded_options = None
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._serialized_options = b'\310\336\037\000'
  _globals['_QUERY'].methods_by_name['Params']._loaded_options = None
  _globals['_QUERY'].methods_by_name['Params']._serialized_options = b'\202\323\344\223\002\037\022\035/lavanet/lava/projects/params'
  _globals['_QUERY'].methods_by_name['Info']._loaded_options = None
  _globals['_QUERY'].methods_by_name['Info']._serialized_options = b'\202\323\344\223\002\'\022%/lavanet/lava/projects/info/{project}'
  _globals['_QUERY'].methods_by_name['Developer']._loaded_options = None
  _globals['_QUERY'].methods_by_name['Developer']._serialized_options = b'\202\323\344\223\002.\022,/lavanet/lava/projects/developer/{developer}'
  _globals['_QUERYPARAMSREQUEST']._serialized_start=185
  _globals['_QUERYPARAMSREQUEST']._serialized_end=205
  _globals['_QUERYPARAMSRESPONSE']._serialized_start=207
  _globals['_QUERYPARAMSRESPONSE']._serialized_end=281
  _globals['_QUERYINFOREQUEST']._serialized_start=283
  _globals['_QUERYINFOREQUEST']._serialized_end=318
  _globals['_QUERYINFORESPONSE']._serialized_start=320
  _globals['_QUERYINFORESPONSE']._serialized_end=445
  _globals['_QUERYDEVELOPERREQUEST']._serialized_start=447
  _globals['_QUERYDEVELOPERREQUEST']._serialized_end=489
  _globals['_QUERYDEVELOPERRESPONSE']._serialized_start=492
  _globals['_QUERYDEVELOPERRESPONSE']._serialized_end=622
  _globals['_QUERY']._serialized_start=625
  _globals['_QUERY']._serialized_end=1069
# @@protoc_insertion_point(module_scope)
