# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/projects/tx.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/projects/tx.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from lavanet.lava.projects import project_pb2 as lavanet_dot_lava_dot_projects_dot_project__pb2
from lavanet.lava.plans import policy_pb2 as lavanet_dot_lava_dot_plans_dot_policy__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1elavanet/lava/projects/tx.proto\x12\x15lavanet.lava.projects\x1a\x11\x61mino/amino.proto\x1a#lavanet/lava/projects/project.proto\x1a\x1flavanet/lava/plans/policy.proto\x1a\x14gogoproto/gogo.proto\"\x84\x01\n\nMsgAddKeys\x12\x0f\n\x07\x63reator\x18\x01 \x01(\t\x12\x0f\n\x07project\x18\x02 \x01(\t\x12=\n\x0cproject_keys\x18\x03 \x03(\x0b\x32!.lavanet.lava.projects.ProjectKeyB\x04\xc8\xde\x1f\x00:\x15\x8a\xe7\xb0*\x10projects/AddKeys\"\x14\n\x12MsgAddKeysResponse\"\x84\x01\n\nMsgDelKeys\x12\x0f\n\x07\x63reator\x18\x01 \x01(\t\x12\x0f\n\x07project\x18\x02 \x01(\t\x12=\n\x0cproject_keys\x18\x03 \x03(\x0b\x32!.lavanet.lava.projects.ProjectKeyB\x04\xc8\xde\x1f\x00:\x15\x8a\xe7\xb0*\x10projects/DelKeys\"\x14\n\x12MsgDelKeysResponse\"u\n\x0cMsgSetPolicy\x12\x0f\n\x07\x63reator\x18\x01 \x01(\t\x12\x0f\n\x07project\x18\x02 \x01(\t\x12*\n\x06policy\x18\x03 \x01(\x0b\x32\x1a.lavanet.lava.plans.Policy:\x17\x8a\xe7\xb0*\x12projects/SetPolicy\"\x16\n\x14MsgSetPolicyResponse\"\x8e\x01\n\x18MsgSetSubscriptionPolicy\x12\x0f\n\x07\x63reator\x18\x01 \x01(\t\x12\x10\n\x08projects\x18\x02 \x03(\t\x12*\n\x06policy\x18\x03 \x01(\x0b\x32\x1a.lavanet.lava.plans.Policy:#\x8a\xe7\xb0*\x1eprojects/SetSubscriptionPolicy\"\"\n MsgSetSubscriptionPolicyResponse2\x9a\x03\n\x03Msg\x12W\n\x07\x41\x64\x64Keys\x12!.lavanet.lava.projects.MsgAddKeys\x1a).lavanet.lava.projects.MsgAddKeysResponse\x12W\n\x07\x44\x65lKeys\x12!.lavanet.lava.projects.MsgDelKeys\x1a).lavanet.lava.projects.MsgDelKeysResponse\x12]\n\tSetPolicy\x12#.lavanet.lava.projects.MsgSetPolicy\x1a+.lavanet.lava.projects.MsgSetPolicyResponse\x12\x81\x01\n\x15SetSubscriptionPolicy\x12/.lavanet.lava.projects.MsgSetSubscriptionPolicy\x1a\x37.lavanet.lava.projects.MsgSetSubscriptionPolicyResponseB-Z+github.com/lavanet/lava/v2/x/projects/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.projects.tx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/lavanet/lava/v2/x/projects/types'
  _globals['_MSGADDKEYS'].fields_by_name['project_keys']._loaded_options = None
  _globals['_MSGADDKEYS'].fields_by_name['project_keys']._serialized_options = b'\310\336\037\000'
  _globals['_MSGADDKEYS']._loaded_options = None
  _globals['_MSGADDKEYS']._serialized_options = b'\212\347\260*\020projects/AddKeys'
  _globals['_MSGDELKEYS'].fields_by_name['project_keys']._loaded_options = None
  _globals['_MSGDELKEYS'].fields_by_name['project_keys']._serialized_options = b'\310\336\037\000'
  _globals['_MSGDELKEYS']._loaded_options = None
  _globals['_MSGDELKEYS']._serialized_options = b'\212\347\260*\020projects/DelKeys'
  _globals['_MSGSETPOLICY']._loaded_options = None
  _globals['_MSGSETPOLICY']._serialized_options = b'\212\347\260*\022projects/SetPolicy'
  _globals['_MSGSETSUBSCRIPTIONPOLICY']._loaded_options = None
  _globals['_MSGSETSUBSCRIPTIONPOLICY']._serialized_options = b'\212\347\260*\036projects/SetSubscriptionPolicy'
  _globals['_MSGADDKEYS']._serialized_start=169
  _globals['_MSGADDKEYS']._serialized_end=301
  _globals['_MSGADDKEYSRESPONSE']._serialized_start=303
  _globals['_MSGADDKEYSRESPONSE']._serialized_end=323
  _globals['_MSGDELKEYS']._serialized_start=326
  _globals['_MSGDELKEYS']._serialized_end=458
  _globals['_MSGDELKEYSRESPONSE']._serialized_start=460
  _globals['_MSGDELKEYSRESPONSE']._serialized_end=480
  _globals['_MSGSETPOLICY']._serialized_start=482
  _globals['_MSGSETPOLICY']._serialized_end=599
  _globals['_MSGSETPOLICYRESPONSE']._serialized_start=601
  _globals['_MSGSETPOLICYRESPONSE']._serialized_end=623
  _globals['_MSGSETSUBSCRIPTIONPOLICY']._serialized_start=626
  _globals['_MSGSETSUBSCRIPTIONPOLICY']._serialized_end=768
  _globals['_MSGSETSUBSCRIPTIONPOLICYRESPONSE']._serialized_start=770
  _globals['_MSGSETSUBSCRIPTIONPOLICYRESPONSE']._serialized_end=804
  _globals['_MSG']._serialized_start=807
  _globals['_MSG']._serialized_end=1217
# @@protoc_insertion_point(module_scope)
