# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/fixationstore/fixation.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/fixationstore/fixation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from lavanet.lava.timerstore import timer_pb2 as lavanet_dot_lava_dot_timerstore_dot_timer__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)lavanet/lava/fixationstore/fixation.proto\x12\x1alavanet.lava.fixationstore\x1a\x14gogoproto/gogo.proto\x1a#lavanet/lava/timerstore/timer.proto\"}\n\x05\x45ntry\x12\r\n\x05index\x18\x01 \x01(\t\x12\r\n\x05\x62lock\x18\x02 \x01(\x04\x12\x10\n\x08stale_at\x18\x03 \x01(\x04\x12\x10\n\x08refcount\x18\x04 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x12\x11\n\tdelete_at\x18\x06 \x01(\x04\x12\x11\n\tis_latest\x18\x07 \x01(\x08\"j\n\x0eGenesisEntries\x12\r\n\x05index\x18\x01 \x01(\t\x12\x0f\n\x07is_live\x18\x02 \x01(\x08\x12\x38\n\x07\x65ntries\x18\x03 \x03(\x0b\x32!.lavanet.lava.fixationstore.EntryB\x04\xc8\xde\x1f\x00\"\xa3\x01\n\x0cGenesisState\x12\x0f\n\x07version\x18\x01 \x01(\x04\x12\x41\n\x07\x65ntries\x18\x02 \x03(\x0b\x32*.lavanet.lava.fixationstore.GenesisEntriesB\x04\xc8\xde\x1f\x00\x12?\n\ntimerstore\x18\x03 \x01(\x0b\x32%.lavanet.lava.timerstore.GenesisStateB\x04\xc8\xde\x1f\x00\x42\x32Z0github.com/lavanet/lava/v2/x/fixationstore/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.fixationstore.fixation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/lavanet/lava/v2/x/fixationstore/types'
  _globals['_GENESISENTRIES'].fields_by_name['entries']._loaded_options = None
  _globals['_GENESISENTRIES'].fields_by_name['entries']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['entries']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['entries']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['timerstore']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['timerstore']._serialized_options = b'\310\336\037\000'
  _globals['_ENTRY']._serialized_start=132
  _globals['_ENTRY']._serialized_end=257
  _globals['_GENESISENTRIES']._serialized_start=259
  _globals['_GENESISENTRIES']._serialized_end=365
  _globals['_GENESISSTATE']._serialized_start=368
  _globals['_GENESISSTATE']._serialized_end=531
# @@protoc_insertion_point(module_scope)
