# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/dualstaking/delegate.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/dualstaking/delegate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'lavanet/lava/dualstaking/delegate.proto\x12\x18lavanet.lava.dualstaking\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\"\x86\x01\n\nDelegation\x12\x10\n\x08provider\x18\x01 \x01(\t\x12\x0f\n\x07\x63hainID\x18\x02 \x01(\t\x12\x11\n\tdelegator\x18\x03 \x01(\t\x12/\n\x06\x61mount\x18\x04 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"\x1e\n\tDelegator\x12\x11\n\tproviders\x18\x01 \x03(\tB0Z.github.com/lavanet/lava/v2/x/dualstaking/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.dualstaking.delegate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github.com/lavanet/lava/v2/x/dualstaking/types'
  _globals['_DELEGATION'].fields_by_name['amount']._loaded_options = None
  _globals['_DELEGATION'].fields_by_name['amount']._serialized_options = b'\310\336\037\000'
  _globals['_DELEGATION']._serialized_start=124
  _globals['_DELEGATION']._serialized_end=258
  _globals['_DELEGATOR']._serialized_start=260
  _globals['_DELEGATOR']._serialized_end=290
# @@protoc_insertion_point(module_scope)
