# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/dualstaking/genesis.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/dualstaking/genesis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from lavanet.lava.dualstaking import params_pb2 as lavanet_dot_lava_dot_dualstaking_dot_params__pb2
from lavanet.lava.fixationstore import fixation_pb2 as lavanet_dot_lava_dot_fixationstore_dot_fixation__pb2
from lavanet.lava.timerstore import timer_pb2 as lavanet_dot_lava_dot_timerstore_dot_timer__pb2
from lavanet.lava.dualstaking import delegator_reward_pb2 as lavanet_dot_lava_dot_dualstaking_dot_delegator__reward__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&lavanet/lava/dualstaking/genesis.proto\x12\x18lavanet.lava.dualstaking\x1a\x14gogoproto/gogo.proto\x1a%lavanet/lava/dualstaking/params.proto\x1a)lavanet/lava/fixationstore/fixation.proto\x1a#lavanet/lava/timerstore/timer.proto\x1a/lavanet/lava/dualstaking/delegator_reward.proto\"\xa9\x02\n\x0cGenesisState\x12\x36\n\x06params\x18\x01 \x01(\x0b\x32 .lavanet.lava.dualstaking.ParamsB\x04\xc8\xde\x1f\x00\x12\x45\n\rdelegationsFS\x18\x02 \x01(\x0b\x32(.lavanet.lava.fixationstore.GenesisStateB\x04\xc8\xde\x1f\x00\x12\x44\n\x0c\x64\x65legatorsFS\x18\x03 \x01(\x0b\x32(.lavanet.lava.fixationstore.GenesisStateB\x04\xc8\xde\x1f\x00\x12N\n\x15\x64\x65legator_reward_list\x18\x05 \x03(\x0b\x32).lavanet.lava.dualstaking.DelegatorRewardB\x04\xc8\xde\x1f\x00J\x04\x08\x04\x10\x05\x42\x30Z.github.com/lavanet/lava/v2/x/dualstaking/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.dualstaking.genesis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github.com/lavanet/lava/v2/x/dualstaking/types'
  _globals['_GENESISSTATE'].fields_by_name['params']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['params']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['delegationsFS']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['delegationsFS']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['delegatorsFS']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['delegatorsFS']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['delegator_reward_list']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['delegator_reward_list']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE']._serialized_start=259
  _globals['_GENESISSTATE']._serialized_end=556
# @@protoc_insertion_point(module_scope)
