class django::conf (
  $user,
  $project            = $user,
  $home               = "/home/$user",
  $path               = "$home/project",
  $postgresql_db_user = $user,
  $postgresql_db_name = $project,
  $postgresql_db_pass,
  $certbot            = false,
  $git_branch         = "master",
  $git_name           = undef,
  $timezone           = "America/Montreal",
  $ssh_template       = 'prod',
  $nginx_template     = 'prod',
  $local_settings     = 'prod',
  $venv               = "$home/.venv",
  $uwsgi_processes    = 2,
  $uwsgi_threads      = 4,
  $celery_processes   = 4,
  $deploy             = true,
  $autodeploy         = true,
  $puppet_sh          = '/etc/puppet/sync/sh',
  $swap               = false,
  $react_path         = "$home/react",
  $git_react_name     = undef,
  $git_react_branch   = "master",
) {}
