# Generated by Django 4.2.16 on 2024-09-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('reward_month', models.PositiveBigIntegerField(default=0)),
                ('month_remaining', models.PositiveIntegerField(default=0)),
                ('rpc_node_runners', models.PositiveIntegerField(default=0)),
                ('denom', models.CharField(max_length=32)),
                ('denom_price', models.DecimalField(decimal_places=18, default=0, max_digits=32)),
                ('past_rewards', models.DecimalField(decimal_places=18, default=0, max_digits=32)),
            ],
        ),
    ]
