# Generated by Django 4.2.16 on 2024-10-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "blockchains",
            "0002_chain_coingecko_last_update_alter_chain_network_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="chain",
            name="denom",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
