# Generated by Django 4.2.16 on 2024-09-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0002_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='chain_logos/'),
        ),
    ]
