# Generated by Django 4.2.16 on 2024-10-08 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blockchains", "0003_alter_chain_denom"),
    ]

    operations = [
        migrations.AddField(
            model_name="denom",
            name="coingecko_last_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="chain",
            name="denom",
        ),
    ]
