# Generated by Django 4.2.16 on 2024-09-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0003_chain_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
