# Generated by Django 4.2.16 on 2024-09-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0004_alter_chain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='month',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
