# Generated by Django 4.2.16 on 2024-10-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchains", "0005_remove_chain_denom_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="rpc_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chain",
            name="network",
            field=models.CharField(
                choices=[("mainnet", "Mainnet"), ("testnet", "Testnet")],
                default="mainnet",
                help_text="Tendermintrpc(lava.tendermintrpc.lava.build) or Testnet (lav1.tendermintrpc.lava.build) ",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="denom",
            name="price",
            field=models.DecimalField(
                decimal_places=18, default=0, max_digits=32, verbose_name="Price (USD)"
            ),
        ),
        migrations.AlterField(
            model_name="reward",
            name="reward_type",
            field=models.CharField(
                choices=[("manual", "Manual"), ("onchain", "Onchain")],
                default="manual",
                help_text="Manual rewards will be counted instead of OnChain reward for the same month if both exist.",
                max_length=16,
            ),
        ),
    ]
