# Generated by Django 4.2.16 on 2024-09-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0005_reward_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denom',
            fields=[
                ('ibc_denom', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('denom', models.CharField(max_length=32)),
                ('price_usd', models.DecimalField(decimal_places=18, default=0, max_digits=32)),
            ],
        ),
        migrations.AlterField(
            model_name='reward',
            name='height',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
