# Generated by Django 4.2.16 on 2024-09-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchains', '0006_denom_alter_reward_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chain',
            name='month_remaining',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='reward_month',
        ),
        migrations.RemoveField(
            model_name='denom',
            name='price_usd',
        ),
        migrations.AddField(
            model_name='chain',
            name='future_rewards',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=32),
        ),
    ]
