# Generated by Django 4.2.16 on 2024-10-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchains", "0007_remove_reward_height_reward_price_usd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="denom",
            name="microtoken_factor",
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
