# Generated by Django 4.2.16 on 2024-10-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchains", "0008_denom_microtoken_factor"),
    ]

    operations = [
        migrations.CreateModel(
            name="MicroDenom",
            fields=[
                (
                    "denom",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("ibc_denom", models.CharField(blank=True, max_length=68, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="chain",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="reward",
            name="month",
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Blank (empty) value is a future reward shown as "TBD".',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reward",
            name="price_usd",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=16, null=True
            ),
        ),
        migrations.RemoveField(
            model_name="chain",
            name="network",
        ),
    ]
