# Generated by Django 4.2.16 on 2024-10-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchains", "0011_alter_reward_reward_amount"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="blockrequest",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="blockrequest",
            name="network",
            field=models.CharField(
                choices=[("mainnet", "Mainnet"), ("testnet", "Testnet")],
                default="mainnet",
                max_length=12,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blockrequest",
            unique_together={("chain", "height", "network")},
        ),
    ]
