# Generated by Django 4.2.16 on 2024-10-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchains", "0013_chain_estimated_apr"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="denom",
            name="microtoken_factor",
            field=models.PositiveBigIntegerField(blank=True, default=1),
        ),
    ]
