# Generated by Django 4.2.16 on 2024-10-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchains", "0014_chain_is_active_alter_denom_microtoken_factor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chain",
            name="months_remaining",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
