# Generated by Django 4.2.16 on 2024-10-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchains", "0015_alter_chain_months_remaining"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="future_rewards_usd",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=36),
        ),
        migrations.AddField(
            model_name="chain",
            name="past_rewards_usd",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=36),
        ),
    ]
