# Generated by Django 4.2.16 on 2024-10-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blockchains", "0016_chain_future_rewards_usd_chain_past_rewards_usd"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chain",
            old_name="months_remaining",
            new_name="rewards_end_month",
        ),
        migrations.RenameField(
            model_name="chain",
            old_name="rewards_per_month",
            new_name="current_rewards",
        ),
    ]
