# Generated by Django 4.2.16 on 2024-10-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchains", "0017_rename_months_remaining_chain_rewards_end_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="name_override",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
