# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/spec/genesis.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/spec/genesis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from lavanet.lava.spec import params_pb2 as lavanet_dot_lava_dot_spec_dot_params__pb2
from lavanet.lava.spec import spec_pb2 as lavanet_dot_lava_dot_spec_dot_spec__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1flavanet/lava/spec/genesis.proto\x12\x11lavanet.lava.spec\x1a\x14gogoproto/gogo.proto\x1a\x1elavanet/lava/spec/params.proto\x1a\x1clavanet/lava/spec/spec.proto\"\x83\x01\n\x0cGenesisState\x12/\n\x06params\x18\x01 \x01(\x0b\x32\x19.lavanet.lava.spec.ParamsB\x04\xc8\xde\x1f\x00\x12/\n\x08specList\x18\x02 \x03(\x0b\x32\x17.lavanet.lava.spec.SpecB\x04\xc8\xde\x1f\x00\x12\x11\n\tspecCount\x18\x03 \x01(\x04\x42)Z\'github.com/lavanet/lava/v2/x/spec/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.spec.genesis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/lavanet/lava/v2/x/spec/types'
  _globals['_GENESISSTATE'].fields_by_name['params']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['params']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['specList']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['specList']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE']._serialized_start=139
  _globals['_GENESISSTATE']._serialized_end=270
# @@protoc_insertion_point(module_scope)
