# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/spec/params.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/spec/params.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1elavanet/lava/spec/params.proto\x12\x11lavanet.lava.spec\x1a\x14gogoproto/gogo.proto\"\x8c\x01\n\x06Params\x12+\n\x05maxCU\x18\x02 \x01(\x04\x42\x1c\xf2\xde\x1f\x18yaml:\"max_compute_units\"\x12I\n\x1a\x61llowlisted_expedited_msgs\x18\x03 \x03(\tB%\xf2\xde\x1f!yaml:\"allowlisted_expedited_msgs\":\x04\x98\xa0\x1f\x00J\x04\x08\x01\x10\x02\x42)Z\'github.com/lavanet/lava/v2/x/spec/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.spec.params_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/lavanet/lava/v2/x/spec/types'
  _globals['_PARAMS'].fields_by_name['maxCU']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['maxCU']._serialized_options = b'\362\336\037\030yaml:\"max_compute_units\"'
  _globals['_PARAMS'].fields_by_name['allowlisted_expedited_msgs']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['allowlisted_expedited_msgs']._serialized_options = b'\362\336\037!yaml:\"allowlisted_expedited_msgs\"'
  _globals['_PARAMS']._loaded_options = None
  _globals['_PARAMS']._serialized_options = b'\230\240\037\000'
  _globals['_PARAMS']._serialized_start=76
  _globals['_PARAMS']._serialized_end=216
# @@protoc_insertion_point(module_scope)
