# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lavanet/lava/spec/spec_add_proposal.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lavanet/lava/spec/spec_add_proposal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from lavanet.lava.spec import spec_pb2 as lavanet_dot_lava_dot_spec_dot_spec__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)lavanet/lava/spec/spec_add_proposal.proto\x12\x11lavanet.lava.spec\x1a\x14gogoproto/gogo.proto\x1a\x1clavanet/lava/spec/spec.proto\"m\n\x0fSpecAddProposal\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12,\n\x05specs\x18\x03 \x03(\x0b\x32\x17.lavanet.lava.spec.SpecB\x04\xc8\xde\x1f\x00:\x08\x88\xa0\x1f\x00\x98\xa0\x1f\x00\x42-Z\'github.com/lavanet/lava/v2/x/spec/types\xa8\xe2\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lavanet.lava.spec.spec_add_proposal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/lavanet/lava/v2/x/spec/types\250\342\036\001'
  _globals['_SPECADDPROPOSAL'].fields_by_name['specs']._loaded_options = None
  _globals['_SPECADDPROPOSAL'].fields_by_name['specs']._serialized_options = b'\310\336\037\000'
  _globals['_SPECADDPROPOSAL']._loaded_options = None
  _globals['_SPECADDPROPOSAL']._serialized_options = b'\210\240\037\000\230\240\037\000'
  _globals['_SPECADDPROPOSAL']._serialized_start=116
  _globals['_SPECADDPROPOSAL']._serialized_end=225
# @@protoc_insertion_point(module_scope)
